== 2.1 逻辑与的规则

我们先来确定满足一致性的逻辑与的规则,即AB的似真度与分开的A和B的似真度之间的关系。特定的，考虑AB|C。考虑到推理过程有点复杂，我们将从几个不同的角度来审视。

首先注意到,判定AB为真的过程可以分解成为分开判定A和B。机器人可以采取的步骤是:

 (1) 判定B为真；                             （B|C）
 (2) 在接受B为真的条件下，判定A为真。            （A|BC）

或者，等价的:

 (1') 判定A为真；                             （A|C）
 (2') 在接受A为真的条件下，判定B为真。            （B|AC）

在每种情况下，每一步都对应着的一个似真度。

现在让我们详细描述第一种步骤。如果AB命题为真则要求B必须为真.因此需要考虑B|C的似真度。接着,如果B为真则进一步要求A为真,因此还需要考虑A|BC的似真度。但如果B是假的，则AB必然为假，无论A的真假，这可用$$ A|\bar{B}C $$来表示。如果机器人先判断B，那么只有命题B为真时，才有必要考虑命题A的似真度。因此，如果机器人知道B|C和A|BC，那么就不需要知道A|C,因为这没有提供关于AB任何更多的信息。

类似的,也不需要考虑A|B和B|A,因为在确定C为真的情况下,不考虑C真假时的A或B的似真度和我们的判定没有任何关系.举例来说,如果机器人现在已经确定地球是圆的,那么处理宇宙相关的命题(各种极端情况)时就不需要关心那些在不确定地球是圆的的情况下的观点.

因为逻辑与满足交换律，即AB=BA，我们可以交换上面陈述中的A和B.即A|C和B|AC将同样有助于确定AB|C=BA|C。按从上面任一种步骤,机器人对AB|C都应得出相同的值，即要符合基础公理(Ⅲa)的一致性条件。

我们可以用更明确的形式来阐述。(AB|C)是B|C和A|BC的一个函数:

 (AB|C)=F[(B|C),(A|BC)]   (2.1)

现在，如果上面的推理看起来不那么显而易见的话，让我们换种方式。例如，另一种可能的形式是:

 (AB|C)=F[(A|C),(B|C)]     (2.2)

不过容易看出，这种方式的任何关系都不能满足基础公理(Ⅱ)的定性条件。当给定C时命题A的似真度可能很高，同时在给定C时命题B的似真度也可能很高，但命题AB的似真度既可能很高也可能很低。

举例来说，你遇到了一个人,很可能他有蓝色的眼睛,很可能有黑色的头发。如果二者都为真，看起来可能性也很高。从另一方面说，这个人可能左眼是蓝色的,也可能右眼是棕色，但这个人的左眼是蓝色的而且右眼是棕色的则是件令人难以置信的事。当应用公式(2.2)时,没有什么额外的办法可以保证我们一定会将这种额外影响考虑进来。使用这个函数关系,机器人就无法完成和人一样的推理，即使是定性的也不行。

但除此以外还有其他可能的函数关系。我们可以尝试所有可能的方式,穷举式的证明,可以组织如下。定义实数为:

 u=(AB|C), v=(A|C), w=(B|AC), x=(B|C), y=(A|BC)  (2.3)

如果u可以表示为v,w,x,y中的两个或两个以上的函数，则一共有11种可能的方式。你可以列出每一种方式，然后对照各种极端情况来验证一下,就像上面棕色蓝色眼睛的例子一样(这是一个抽象陈述︰A蕴含着B为假)。其他的极端情况有A=B,A=C,$$ C\Rightarrow\bar{A} $$等等。进行了这些繁琐的分析后，Tribus (1969)发现除了两种方式外,其他的都会在一些极端情况下违反常识。这剩余的两种方式分别是u=F(x,y)和u=F(w,v)，正好是我们前面推理得出的两个函数形式。

现在考虑第一章中所讨论的定性条件。假设先验信息发生了变化$$C \to C' $$，导致命题B的似真度增加而命题A的似真度不变，

 B|C' > B|C, (2.4)
 A|BC' = A|BC, (2.5)

根据常识,AB的可信度应该增加，而不是减少：

 AB|C' ≥ AB|C,   (2.6)

仅当且当A|BC是不可能时等号成立。类似的，给定先验信息C"有

 B|C" = B|C,    (2.7)
 A|BC" > A|BC,  (2.8)

我们要求在

 AB|C" ≥ AB|C, (2.9)

中，仅当给定C时命题B不可能发生时等号成立（那么在给定C"时A|BC依然不可能发生,即使A|BC未被定义）。进一步的，函数F(x,y)应该是连续的，否则等式(2.1)右边似真度的一个任意小的增加，可能导致AB|C似真度的巨大增加。

总之，F(x,y)必须是x和y的连续单调递增函数。如果我们假设它是可导的（可导不是必要条件，见（2.13）之后的讨论），那么有

 $$ F_1(x,y) \equiv { \partial F \over \partial x} \ge 0 $$   (2.10a)

当且仅当y表示不可能时取等号；并且

 $$ F_2(x,y) \equiv { \partial F \over \partial y} \ge 0 $$   (2.10b)

当且仅当x表示不可能时取等号。注意在这种表示法中,为了以后的需要,$$F_i$$表示对F的第i个自变量进行求导，无论第i个自变量是什么。

接下来我们考虑基本公理（Ⅲa）的“结构”一致性。假设我们尝试确定（ABC|D）的似真度,即三个命题同时为真的似真度。事实上，因为布尔代数满足结合律：ABC=(AB)C=A(BC)，所有以两种顺序来计算。如果计算规则要满足一致性，那么用任何顺序来计算，得到结果应该是一样的。我们可以先将BC看成单一命题，然后应用(2.1)：

 (ABC|D) = F[(BC|D), (A|BCD)],   (2.11)

然后对于似真度BC|D，我们可以再次应用(2.1)得到

 (ABC|D) = F{F[(C|D), (B|CD)], (A|BCD)}.   (2.12a)

但同样也可以先将AB看成单一命题。按此顺序可以推出另一个表达式︰

 (ABC|D) = F[(C|D), (AB|CD)] = F{(C|D), F[(B|CD), (A|BCD)]}.   (2.12b)

如果希望逻辑积规则可以用来表示一致性推理，那么表达式(2.12a)和(2.12b)必须始终是相等的。因此机器人能够进行一致性推理的必要条件，应满足下面的函数等式:

 F[F(x, y), z] = F[x, F(y, z)].    (2.13)

这个方程在数学中有悠久的历史，从N.H.Abel (1826)的工作开始。Acz´el (1966)在他关于函数等式的巨著中，十分恰当地叫做‘结合性方程’，并列出98篇讨论或使用它的参考文献。Acz´el在不要求可微的前提下,推导出了通用解(2.27).不幸的是，他的证明在他的书中用了11页(第256-267页)的篇幅（同样可见于Acz´el，1987）。下面给出的是R.T.Cox（1961）的简洁证明，前提是满足可微性,更多细节请参见在附录B。

显然(2.13)拥有平凡解即F(x,y)=常数。但这违反了我们的单调性要求(2.10)，而且在任何情况下对我们的目标都是毫无用处。除非(2.13)有一个非平凡解，否则我们的方法就会失败；因此我们要找到一个通用的非平凡解。使用下面的简化:

 u≡F(x,y),  v≡F(y,z),   (2.14)

但(x,y,z)仍作为独立变量，函数方程为

 F(x,v) = F(u,z).     (2.15)

两边对x和y分别求微分，应用(2.10)的表示有:

 $$ F_1(x,v)=F_1(u,z)F_1(x,y) $$
 $$ F_2(x,v)F_1(y,z)=F_1(u,z)F_2(x,y) $$     (2.16)

从这些方程中将$$F_1(u,z)$$消掉得到

 $$G(x,v)F_1(y,z)=G(x,y) $$    (2.17)

这里记$$G(x,y)\equiv F_2(x,y)/F_1(x,y)$$。显然，(2.17)的左边必须独立于z。此时，(2.17)可以等价的写为

 $$ G(x,v)F_2(y,z)=G(x,y)G(y,z) $$   (2.18)

同时将(2.17)和(2.18)的左边分别用U,V来表示,我们可证$$\partial V/ \partial y = \partial U/ \partial z $$。则G(x,y)G(y,z)必然独立于y。最通用的函数G(x,y)具有的性质是:

 $$ G(x,y) = r {H(x) \over H(y)} $$  (2.19)

这里的r是一个常数，H(x)是任意函数的。在此情况下，G>0因为F是单调的，所以我们要求r>0，同时H(x)在值域上正负不变。应用(2.19)、(2.17),则(2.18)变为

 $$F_1(y,z)={H(v) \over H(y)} $$    (2.20)
 $$F_2(y,z)=r {H(v) \over H(z)} $$  (2.21)

则$$ dv=dF(y,z)=F_1 dy + F_2 dz $$的变为:

 $$ {dv \over H(v)} = {dy \over H(y)} + r {dz \over H(z)} $$    (2.22)

或者，积分的形式

 $$ w[F(y,z)]=w(v)=w(y)w^r(z) $$   (2.23)

其中

 $$ w(x) \equiv exp \{ \int^x {dx \over H(x)} \} $$  (2.24)

积分没有下界表示w包含一个任意的乘法因子。但是使用(2.15)中的函数w(.)以及应用(2.23)，我们得到$$ w(x)w^r (v)=w(u)w^r (z) $$；再次应用(2.23)，我们的函数等式变为:

 $$ w(x)w^r(y)[w(z)]^{r2}=w(x)w^r(y)w^r(z) $$    (2.25)

这样在仅当r=1时我们得到了一个非平凡解，同时最终结果可以表示为下面两者之一：

 $$ w[F(x,y)]=w(x)w(y) $$  (2.26)

或

 $$ F(x,y)=w^{-1}[w(x)w(y)] $$   (2.27)

根据逻辑乘法满足结合律和交换律,我们得到的关系必须满足下面的函数形式:

 $$ w(AB|C)=w(A|BC)w(B|C)=w(B|AC)w(A|C) $$   (2.28)

接下来我们称此为乘法规则。由(2.24)的构造可知，w(x)必须是取值为正的单调连续函数，由H(x)的正负而决定是递增还是递减,在现阶段增减都无所谓。

结果(2.28)是根据基本公理（Ⅲa）的一致性得出的一个必要条件。反过来，显然(2.28)也足以确保任意个单命题组成的复合命题的一致性。例如，根据(2.12),我们可以用很多种方式来分解(ABCDEFG|H）,但只要满足(2.28)，得到的结果就都是一样的。

与常识保持定性一致得要求给函数w(x)施加了进一步的限制。例如，在(2.28)的第一个形式中假设给定C时A是确定的。然后，在满足知识C的"逻辑环境"中，命题AB和B是相同的,即一个为真当且仅当另一个为真。基于所有我们在第1章中讨论的基本公理，有相同的真值的命题的似真度应该相等：

 AB|C=B|C, (2.29)

同时还有

 A|BC=A|C (2.30)

因为如果给定C下A已经确定（例如,C蕴含A），然后，在给定另一个与C不冲突的信息B，A仍然确定的。在这种情况下，(2.28)简化为

 w(B|C) = w(A|C)w(B|C),  (2.31)

不论B的似真度为何,对机器人而言这必然成立。所以，函数w(x)必须具有性质:

 确定性可以用w(A|C) = 1来表示.   (2.32)

现在，假设给定C的条件下A是不可能发生的。则给定C的条件下，命题AB也是不可能发生的：

 AB|C = A|C,      (2.33)

同时，如果给定C的条件下A已经是不可能发生的，（例如C蕴含$$\bar{A} $$）,然后,给定任何与C不冲突的信息B时，A仍然是不可能的：

 A|BC = A|C.   (2.34)

此处的(2.28)将被简化为

 w(A|C) = w(A|C)w(B|C),     (2.35)

并且同样的，无论B似真度为何此方程必然成立。w(A│C)仅有两个取值可以满足此条件:零或$$+\infty$$（可以排除$$-\infty$$，因为根据连续性的要求则W(B|C)可以取负值,从而和(2.35)矛盾)。

总之，与常识的定性保持对应要求w(x)是正的单调连续函数。它可以单调增或单调减。如果是单调增，它的值域必须是从表示不可能的0递增到表示确定的1。如果它是单调减的，其值域必须从表示不可能的$$\infty$$递减到表示确定的1。到目前为止，我们的条件没有要求w在区间内是如何变化的。

然而，这两种表示方式在实质上内容上是没有差别的。给定任一函数$$w_1 (x)$$，满足上述要求并且用$$\infty$$表示不可能，我们可以定义一个新的函数$$w_2 (x) \equiv 1/w_1 (x)$$，它同样满足上述要求且用0来表示不可能。因此，按惯例选择0≤w(x)≤1并不失一般性；也就是说，仅考虑实质而言，此形式已经将所有和基本公理相一致性的可能性包括在内了。（读者可以验证，我们可以选择相反的惯例,基于此来发展的整个理论和应用，同样进行的很好,实质相同只是形式稍显陌生。）

