== 2.3 定性属性

现在让我们来看看基于(2.63)和(2.64)得出的理论，与演绎推理理论和第一章中的各种定性推理的关系。首先，很明显的在极限p(A|B)->0或p(A|B)->1的情况下，和规则(2.64)表述了亚里士多德逻辑的原始假定：如果A为真，则{%math%}\bar{A}{%endmath%}必为假，等等。

实际上,强三段论(1.1)、(1.2)和基于此衍生出的组成了所有逻辑。现在用蕴含符号(1.14)来表述大前提：

 $$ A \Rightarrow B A \Rightarrow B $$  (2.68)
 A为真 B为假
 _____ _____
 B为真 A为假

以及由此得出的无尽结果。如果让C来作为它们的大前提:

 $$ C \equiv A \Rightarrow B $$  (2.69)

则这些推理与积准则相对应的形式分别是：

 $$ p(B|AC)={p(AB|C) \over p(A|C)},   p(A|\bar{B}C)={ p(A\bar{B}|C) \over p(\bar{B}|C) } $$  (2.70)

但由(2.68)我们得到p(AB|C)=p(A|C)和{%math%}p(A\bar{B}|C)=0{%endmath%}，并且(2.70)可以简化为

 $$ p(B|AC)=1, p(A|\bar{B}C)=0 $$  (2.71)

就如论断(2.68)中所表述的那样。简单的说,关系是：亚里士多德的演绎逻辑是合情推理规则的极限形式，就如机器人会变得越来越确信它的结论。

但是我们的规则还有演绎逻辑中没有的东西：量化的弱三段论(1.3)和(1.4)。为了显示初始的定性陈述总是可以从现有规则中得出，注意第一个弱三段论:

 $$ A \Rightarrow B $$  (2.72)
 B为真
 ______
 所以,A可信度增加

以形式

 $$ p(A|BC)=p(A|C){ p(B|AC) \over p(B|C)}. $$  (2.73)

与积规则(2.63)相对应.但是由(2.68),得到p(B|AC)=1，同时因为p(B|C)<=1，(2.73)给出的

 $$ p(A|BC) \le p(A|C) $$  (2.74)

就如三段论中所声明的。同样的，弱三段论(1.4)

 $$ A \Rightarrow B $$  (2.75)
 A为假
 _____
 所以,B可信度减少

与积准则相一致的形式

 $$ p(B|\bar{A}C)=p(B|C){ p(\bar{A}|BC) \over p(\bar{A}|C)}. $$  (2.76)

但是由(2.74)得到{%math%}p(\bar{A}|BC)<=p(\bar{A}|C){%endmath%}，并且(2.76)给出

 $$ p(B|\bar{A}C) \le p(B|C), $$  (2.77)

就如论断中所声明的。

最后，警察现在的论断(1.5)，虽然当用抽象方式所表述时看起来不够强，但依然被包括在了以(2.73)形式所表述的积规则中。让C如今来表示背景信息（未在(1.5)中明确说出，因为似乎不太需要），“如果命题A为真，所以，命题B为真变得更加合情”这个大前提现在可用形式

 $$ p(B|AC) > p(B|c) $$  (2.78)

表示,而(2.73)立刻给出

 $$ p(A|BC) > p(A|C) $$  (2.79)

恰如论断中所声明的。

现在我们拥有的比(2.79)这样的定性表述更多。在第一章里我们想得到但没得到任何答案的问题：是什么决定了,证据B能否让A变得几乎完全肯定的,或者几乎毫无影响呢？从(2.73)得到的答案是，几人p(B|AC)不能大于单位1，只有当p(B|C)很小时，才会显著增加A的似真度。我们看到的绅士的行为（B）让我非常确定他是个罪犯（A），因为他的行为在背景信息下看来发生的可能性非常之小。没有任何一个警察曾看到过一个无辜的人有那样的行为。另一方面，如果知道A为真则对B的合情度增加小到可以忽略不计，所以观察到B导致对A的似真度的增加也可以忽略不计。

我们可以给出更多这种形式的对比。实际上，许多作者已经注意并描述了这些规则与常识在定性上的完整的对应，包括Keynes (1921), Jeffreys (1939), P ´olya (1945, 1954), R. T. Cox(1961), Tribus (1969), de Finetti (1974a,b),和Rosenkrantz (1977)。P´olya的描述在第一章和前言里都已简单提及，同时我们刚刚也将Cox的描述更完整的说了一遍。然而，我们现在的目的是要继续推进如何在应用中进行量化，所以我们要回到基础理论的发展。

