== 2.6 评论

It has taken us two chapters of close reasoning to get back to the point (2.99) from which Laplace started some 180 years ago. We shall try to understand the intervening period, as a weird episode of history, throughout the rest of the present work. The story is so complicated that we can unfold it only gradually, over the next ten chapters. To make a start on this, let us consider some of the questions often raised about the use of probability theory as an extension of logic.

我们已经用了两章来讨论推理,从180年前拉普拉斯的观点(2.99)开始.在本书的余下部分,我们将试图了解在从此之后的,充满着不可思议的戏剧性历史,我们将在接下来的十章中逐步展开这错综复杂的整个故事.作为开始,让我们先看看把概率论用于扩展的逻辑时常常被提出的问题。

=== 2.6.1 主观与客观

These words are abused so much in probability theory that we try to clarify our use of them. In the theory we are developing, any probability assignment is necessarily ‘subjective’ in the sense that it describes only a state of knowledge, and not anything that could be measured in a physical experiment. Inevitably, someone will demand to know: ‘Whose state of knowledge?’ The answer is always: ‘That of the robot – or of anyone else who is given the same information and reasons according to the desiderata used in our derivations in this chapter.’

在概率论中,对这两个词的滥用是如此之多,有必要澄清一下我们的用法。在我们发展的理论中,任何赋予概率的行为一定是“主观”的,因为这只是为了描述知识的一个状态,而不是可以在物理实验中测量的任何东西。不可避免的是,有人会问：“是谁的知识状态？”答案都是：“机器人-或者任何人,拥有相同的信息,并且按照本章中派生的基础公理的进行推理。“

Anyone who has the same information, but comes to a different conclusion than our robot, is necessarily violating one of those desiderata. While nobody has the authority to forbid such violations, it appears to us that a rational person, should he discover that he was violating one of them, would wish to revise his thinking (in any event, he would surely have difficulty in persuading anyone else, who was aware of that violation, to accept his conclusions).

无论是谁,拥有同样的信息,确得出了和机器人不一样的结论,那么他必然是违反了某个基础公理.虽然没有权威说不得违反,对我们而言,如果理性人一旦发现自己违反了基础公理,必然愿意改正自己(无论如何他将难以说服任何人,如果那个人意识到这与基础公理相矛盾）.

Now, it was just the function of our interface desiderata (IIIb), (IIIc) to make these probability assignments completely ‘objective’ in the sense that they are independent of the personality of the user. They are a means of describing (or, what is the same thing, of encoding) the information given in the statement of a problem, independently of whatever personal feelings (hopes, fears, value judgments, etc.) you or I might have about the propositions involved. It is ‘objectivity’ in this sense that is needed for a scientifically respectable theory of inference.

现在,基础公理中关于接口的(IIIb)和(IIIc)使得概率取值是完全“客观”的,即独立于使用者的偏好。它们是一种对问题陈述中所提供的信息进行描述（或者可以说是一种编码方式）的手段,不管你好事我的对相关命题的个人感受（希望,恐惧,价值判断等）。从这个意义上讲,这是一个科学上可接受的推论理论所需要的“客观性”。

=== 2.6.2 哥德尔定理

To answer another inevitable question, we recapitulate just what has and what has not been proved in this chapter. The main constructive requirement which determined our product and sum rules was the desideratum (IIIa) of ‘structural consistency’. Of course, this does not mean that our rules have been proved consistent; it means only that any other rules which represent degrees of plausibility by real numbers, but which differ in content from ours, will lead necessarily either to inconsistencies or violations of our other desiderata. 

为了回答另一个无法回避的问题,我们总结一下在本章中已经证明了和还未证明的部分.按照"结构一致性的"基本公理(IIIa)的要求,我们构建了乘法和加法的规则.当然,这并没有证明这些规则是一致的;只是说明其他任何一个同样用实数表示似真度,但内容和我们不同的规则集,都必然与其他的基本公理相矛盾或冲突.

A famous theorem of Kurt Gödel (1931) states that no mathematical system can provide a proof of its own consistency. Does this prevent us from ever proving the consistency of probability theory as logic? We are not prepared to answer this fully, but perhaps we can clarify the situation a little.

著名的哥德尔定理声称,没有一个数学系统能够证明自身是一致的.但这是否意味着我们无法证明用于逻辑的概率论的一致性?我们不会给出完整的回答,不过我们可以做出一些澄清.

Firstly, let us be sure that ‘inconsistency’ means the same thing to us and to a logician. What we had in mind was that if our rules were inconsistent, then it would be possible to derive contradictory results from valid application of them; for example, by applying the rules in two equally valid ways, one might be able to derive both P(A|BC) = 1/3 and P(A|BC) = 2/3. Cox’s functional equations sought to guard against this. Now, when a logician says that a system of axioms $$\{A_1,A_2, ... , A_n\}$$ is inconsistent, he means that a contradiction can be deduced from them; i.e. some proposition Q and its denial $$\bar{Q}$$ are both deducible. Indeed, this is not really different from our meaning.

首先我们要弄清楚对于"不一致"这个词,我们和逻辑学家的理解是一样的.在我们的看法里,如果说我们的规则是不一致的,那么意味着应用这些规则可以得到矛盾的结论;举例来说,通过两种等价且合法的方式应用规则,可以同时得到结论P(A|BC)=1/3和P(A|BC)=2/3.Cox的函数等式就是为了防止这个问题的出现.现在如果一个逻辑学家说一个基于公理$$\{A_1,A_2,...,A_n\}$$的系统是不一致的,他的意思是从这些公理可以推出矛盾;例如,命题Q及其否命题$$\bar{Q}$$都能被演绎推理得出.这与我们的理解其实并无差别.

To understand the above Gödel result, the essential point is the principle of elementary logic that a contradiction $$A\bar{A}$$ implies all propositions, true and false. (Given any two propositions A and B, we have A⇒(A+B), therefore $$A\bar{A}$$ ⇒ $$\bar{A}(A+B)=\bar{A}A+\bar{A}B$$ ⇒ B.) Then let A = $$\{A_1,A_2,...,A_n\}$$ be the system of axioms underlying a mathematical theory and T any proposition, or theorem, deducible from them: [1]

为了理解哥德尔的结论,本质的一点是基本逻辑原理,即$$A\bar{A}$$蕴涵了所有命题,无论其真假.(给定任何两个命题A和B,则有A⇒(A+B),所以$$A\bar{A}$$ ⇒ $$\bar{A}(A+B)=\bar{A}A+\bar{A}B$$⇒B).然后让A=$$\{A_1,A_2,...,A_n\}$$是一个数学理论的公理,T是任何一个从这些公理演绎推理出的命题或定理,

A ⇒ T. (2.102)

Now, whatever T may assert, the fact that T can be deduced from the axioms cannot prove that there is no contradiction in them, since, if there were a contradiction, T could certainly be deduced from them! 

现在,无论T表述了什么,T可以从公理演绎推理出来的事实并不能证明公理系统中不存在矛盾,因为如果有矛盾存在的话T肯定能被演绎推理得到!

This is the essence of the Gödel theorem, as it pertains to our problems. As noted by Fisher (1956), it shows us the intuitive reason why Gödel’s result is true. We do not suppose that any logician would accept Fisher’s simple argument as a proof of the full Gödel theorem; yet for most of us it is more convincing than Gödel’s long and complicated proof. [2]

这就是哥德尔定理的和我们问题有关的精髓.正如Fisher(1956)注意到的,这展示了哥德尔结论正确性的直觉原因.我们不是在建议逻辑学家们把Fisher的简单论证作为对哥德尔定理的完整证明;只是对我们的大多数来说,这比既长又复杂的证明更易于令人易于接受.

Now suppose that the axioms contain an inconsistency. Then the opposite of T and therefore the contradiction $$\bar{T}T$$ can also be deduced from them:

现在假设公理系统中有矛盾存在,那么T的否定和矛盾命题$$\bar{T}T$$都可演绎得到:

 $$A⇒\bar{T}$$ .    (2.103)

So, if there is an inconsistency, its existence can be proved by exhibiting any proposition T and its opposite $$\bar{T}$$ that are both deducible from the axioms. However, in practice it may not be easy to find a T for which one sees how to prove both T and $$\bar{T}$$. 

所以,如果存在矛盾,那么只要找到任何命题T及其否命题$$\bar{T}$$都能被演绎推理出来就能证明存在矛盾.然而,实际上想要找到并证明T和$$\bar{T}$$往往并不是一件容易的事.

Evidently, we could prove the consistency of a set of axioms if we could find a feasible procedure which is guaranteed to locate an inconsistency if one exists; so Gödel’s theorem seems to imply that no such procedure exists. Actually, it says only that no such procedure derivable from the axioms of the system being tested exists. 

显而易见,如果我们能找到一个切实可行的过程来保证找到矛盾如果真的存在矛盾的话,我们就能证明一个公理系统是否是一致的;所以哥德尔定理似乎暗示了这种过程并不存在.事实上哥德尔定理表述的是,此过程不能从公理系统本身所演绎推理得到.

We shall find that probability theory comes close to this; it is a powerful analytical tool which can search out a set of propositions and detect a contradiction in them if one exists. The principle is that probabilities conditional on contradictory premises do not exist (the hypothesis space is reduced to the empty set). Therefore, put our robot to work; i.e. write a computer program to calculate probabilities p(B|E) conditional on a set of propositions $$E=(E_1E_2...E_n)$$. Even though no contradiction is apparent from inspection, if there is a contradiction hidden in E, the computer program will crash.

我们会发现概率论和这个过程很像,概率论是一个强有力的分析工具,它可以搜索出一组命题并检测其中是否存在矛盾.原理是,概率依赖于前提假设中不存在矛盾(假设空间演绎缩减为空集).因此,当我们的机器人工作的时候,例如一个从一组命题$$E=(E_1E_2...E_n)$$来计算p(B|E)的概率的程序.即使我们没能检测出存在矛盾,但如果E中确实隐藏了矛盾的话,这个程序终将崩溃.

We discovered this ‘empirically’, and, after some thought, realized that it is not a reason for dismay, but rather a valuable diagnostic tool that warns us of unforeseen special cases in which our formulation of a problem can break down.

从"经验"上我们发现了这点,并经过一些思考后,认识到我们不应为此气馁,相反这是一个很有价值的诊断工具,它能够警告我们被公式化的问题可能在某些特殊情况下将会失败.

If the computer program does not crash, but prints out valid numbers, then we know that the conditioning propositions $$E_i$$ are mutually consistent, and we have accomplished what one might have thought to be impossible in view of Gödel’s theorem. But of course our use of probability theory appeals to principles not derivable from the propositions being tested, so there is no difficulty; it is important to understand what Gödel’s theorem does and does not prove.

如果程序没有崩溃,而是输出了合法数值,那么我们就能知道条件命题$$E_i$$是互相一致的,虽然从哥德尔定理角度看这似乎是不可能得到的结果.由于我们用到的概率论基于的原理并非源于被测命题,所以证明矛盾不存在看起来不是很困难;重要的是明白那些是哥德尔定理证明了的,而那些不是.

When Gödel’s theorem first appeared, with its more general conclusion that a mathematical system may contain certain propositions that are undecidable within that system, it seems to have been a great psychological blow to logicians, who saw it at first as a devastating obstacle to what they were trying to achieve. Yet a moment’s thought shows us that many quite simple questions are undecidable by deductive logic. There are situations in which one can prove that a certain property must exist in a finite set, even though it is impossible to exhibit any member of the set that has that property. For example, two persons are the sole witnesses to an event; they give opposite testimony about it and then both die. Then we know that one of them was lying, but it is impossible to determine which one.

当哥德尔定理刚出现的时候,它的普遍性的结论即一个数学系统可能包含一些不能在该系统内判定的命题,这给逻辑学家一个巨大的心理上的打击,他们将其视作达到目标的路上的一个不可逾越的障碍.但略作思考后,我们意思到很多简单的问题都无法通过演绎逻辑来判定.例如在一个有限集合中,可以证明必然存在一种属性,却无法确定是哪个元素具有这个属性.举例来说,一个事件只有两个目击人,他们给出了相反的证词然后都死了.那么我们知道必然有一个人说谎了,却没法知道是谁.

In this example, the undecidability is not an inherent property of the proposition or the event; it signifies only the incompleteness of our own information. But this is equally true of abstract mathematical systems; when a proposition is undecidable in such a system, that means only that its axioms do not provide enough information to decide it. But new axioms, external to the original set, might supply the missing information and make the proposition decidable after all.

在这个例子中,不可判定性既不属于命题,也不属于事件;只是说明了我们拥有的信息是不完全的.但抽象数学系统同样如此,如果系统中有一个命题是不能判定的,只是意味着系统的所有公理未能提供足够的信息来做出判定.但是如果增加原始系统之外的新公理的话,即可以提供那些遗失掉信息的话,我们就可以对该命题做出判定了.

In the future, as science becomes more and more oriented to thinking in terms of information content, Gödel’s result will be seen as more of a platitude than a paradox. Indeed, from our viewpoint ‘undecidability’ merely signifies that a problem is one that calls for inference rather than deduction. Probability theory as extended logic is designed specifically for such problems.

在未来,随着科学愈来愈倾向于基于信息内存来思考,哥德尔的这个结论看起来更像是一个老生常谈而不是悖论.事实上,从我们的观点看,"不能判定"仅仅意味需要对一个问题做出推断更甚于对其进行演绎.将概率论视为广义逻辑恰恰就是为这类问题而设计的.

These considerations seem to open up the possibility that, by going into a wider field by invoking principles external to probability theory, one might be able to prove the consistency of our rules. At the moment, this appears to us to be an open question.

如上的这些考虑看起来是开启了,通过借助概率论之外的原理来进入更广阔的领域的可能性,由此可以证明我们的规则的一致性.在这一刻,对我们而已只是一个开放性问题而已.

Needless to say, no inconsistency has ever been found from correct application of our rules, although some of our calculations will put them to a severe test. Apparent inconsistencies have always proved, on closer examination, to be misapplications of the rules. On the other hand, guided by Cox’s theorems, which tell us where to look, we have never had the slightest difficulty in exhibiting the inconsistencies in the ad hoc rules which abound in the literature, which differ in content from ours and whose sole basis is the intuitive judgment of their inventors. Examples are found throughout this book, but particularly in Chapters 5, 15, and 17.

不必说,在正确应用我们的规则的情况下从未出现过不一致的情况,虽然我们的一些计算需要对其进行严格的测试.出现明显的不一致时,仔细检验后原因总是用错了规则.另一方面,在告诉我们从哪里下手的Cox定理的指导下,我们很容易就能找到在某些文献中使用特殊规则而导致的不一致,这些特殊规则的内容往往与我们的不同,而且其唯一的依据是发明人的直觉判断.这种例子遍布本书,尤其是在第5,15,17章中.

[1] In Chapter 1 we noted the tricky distinction between the weak property of formal implication and the strong one of logical deducibility; by ‘implications of a proposition C’ we really mean ‘propositions logically deducible from C and the totality of other background information’. Conventional expositions of Aristotelian logic are, in our view, flawed by their failure to make explicit mention of background information, which is usually essential to our reasoning, whether inductive or deductive. But, in the present argument, we can understand A as including all the propositions that constitute that background information; then ‘implication’ and ‘logical deducibility’ are the same thing.

在第一章中,我们注意到逻辑演绎的蕴涵的强弱形式之间的微妙区别,说"命题C蕴涵了命题Q",我们其实想表达"命题Q可以从C以及其他所有背景信息中逻辑演绎得出".阿里士多德逻辑的传统解释是,在我们看来,其缺陷是没有显式的指出背景信息,而背景信息恰恰是推断亦或演绎的根本所在.但在我们的论证中,我们理解A包括了所有代表了背景信息的命题,所以"蕴涵"和"逻辑演绎"看起来是同一件事情.

[2] The 1957 edition of Harold Jeffreys’ Scientific Inference (see Jeffreys, 1931) has a short summary of Gödel’s original reasoning which is far clearer and easier to read than any other ‘explanation’ we have seen. The full theorem refers to other matters of concern in 1931 but of no interest to us right now; the above discussion has abstracted the part of it that we need to understand for our present purposes.

注2: 在Harold Jeffreys的1957年版的<科学的推理>(见Jeffresy, 1931)中给出了一个高德尔的精简的原始证明,这个证明比我们见到的任何其他的'解释'都更清晰易懂.定理的完整说明会涉及一些1931年的重要事件,但不在我们现在的关注范围之内;上面的讨论已经将其中与我们相关的部分概括进来了.

=== 2.6.3 韦恩图

donehere
Doubtless, some readers will ask, ‘After the rather long and seemingly unmotivated derivation of the extended sum rule (2.66), which in our new notation now takes the form

毫无疑问一些读者会问,“经过如此冗长乏味的推导,得到的加法规则可以表示如下(2.66)

 P(A+B|C)=P(A|C)+P(B|C)−P(AB|C), (2.104)

why did we not illustrate it by the Venn diagram? That makes its meaning so much clearer.’ (Here we draw two circles labeled A and B, with intersection labeled AB, all within a circle C.)

为什么我们不用维恩图来解释这个公式呢？这样一切就都显而易见了。'（这里我们画了两个圆形,分别标记为A和B,重叠区域标记为AB,以上全部位于圆形C之内。）

The Venn diagram is indeed a useful device, illustrating – in one special case – why the negative term appears in (2.104). But it can also mislead, because it suggests to our intuition more than the actual content of (2.104). Looking at the Venn diagram, we are encouraged to ask, ‘What do the points in the diagram mean?’ If the diagram is intended to illustrate (2.104), then the probability for A is, presumably, represented by the area of circle A; for then the total area covered by circles A, B is the sum of their separate areas, minus the area of overlap, corresponding exactly to (2.104).

维恩图确实是一个有用的方法,说明了--在一个特例中--为什么在(2.104)出现了减号项。但这容易产生误导,似乎暗示了一些在(2.104)之外的东西。看这个维恩图,我们会想问：“图中的点代表了什么？”如果只是为了说明(2.104),那么A的概率大概是由圆圈A的面积表示的。那么圆圈A和B所覆盖的总面积应该是,它们各自区域的总和,减去重叠面积,和(2.104)完全一致。

Now, the circle A can be broken down into nonoverlapping subregions in many different ways; what do these subregions mean? Since their areas are additive, if the Venn diagram is to remain applicable they must represent a refinement of A into the disjunction of some mutually exclusive subpropositions. We can – if we have no mathematical scruples about approaching infinite  limits – imagine this subdivision carried down to the individual points in the diagram. Therefore these points must represent some ultimate ‘elementary’ propositions $$ω_i$$ into which A can be resolved.[3] Of course, consistency then requires us to suppose that B and C can also be resolved into these same propositions $$ω_i$$ .

现在,圆形A可以按多种方式分解为互不重叠的子区域,那么这些子区域代表了什么？由于这些子区域是可以求和的,如果维恩图仍然适用,这表示了A一定可以细化为多个互斥的子命题。我们可以--如果不担心极限情况--想象一下将图不断细分下去直到各个点为止。这些点必然代表一些终极'基本'命题,即$$ω_i$$,A可以解析为这些命题。[注3]当然,一致性要求我们假设B和C也可以解析为这些相同的命题$$ω_i$$。

We have already jumped to the conclusion that the propositions to which we assign probabilities correspond to sets of points in some space, that the logical disjunction A+B stands for the union of the sets, the conjunction AB for their intersection, and that the probabilities are an additive measure over those sets. But the general theory we are developing has no such structure; all these things are properties only of the Venn diagram.

从上面我们已经得到结论,命题对应于一个空间中的点集,逻辑和A+B代表并集,逻辑乘AB对应交集,而概率是对这些集合的满足可加性的度量。 但我们正在发展的一般理论并不具有这种结构,这些属性只存在于维恩图中。

In developing our theory of inference we have taken special pains to avoid restrictive assumptions which would limit its scope; it is to apply, in principle, to any propositions with unambiguous meaning. In the special case where those propositions happen to be statements about sets, the Venn diagram is an appropriate illustration of (2.104). But most of the propositions about which we reason, for example,

在发展我们的推理理论时,我们特别注意避免限制其范围的限制性假设; 它原则上适用于任何具有明确含义的命题。 在这些命题碰巧是关于集合的陈述的特殊情况下,维恩图适用于解释(2.104)。 但是大多数我们推理的命题,例如,

 A ≡ it will rain today, (2.105)
 B ≡ the roof will leak, (2.106)

 A ≡ 今天会下雨, (2.105)
 B ≡ 屋顶会漏水, (2.106)

are simply declarative statements of fact, which may or may not be resolvable into a disjunction of more elementary propositions within the context of our problem.

只是对简单事实的陈述性陈述,在此背景下可能无法解析为更多基本命题。

Of course, one can always force such a resolution by introducing irrelevancies; for example, even though the above-defined B has nothing to do with penguins, we could still resolve it into the disjunction

当然,总是可以引入无关紧要的因素强制对命题进行解析,例如,即使上面定义的B与企鹅无关,我们仍然可以将其解析为

 $$B=BC_1+BC_2+BC_3+...+ BC_N$$ , (2.107)

where $$C_k≡$$ the number of penguins in Antarctica is k. By choosing N sufficiently large, we will surely be making a valid statement of Boolean algebra; but this is idle, and it cannot
help us to reason about a leaky roof.

其中$$C_k≡$$南极洲企鹅的数量是k。通过选择足够大的N,我们肯定会做出有效的布尔代数陈述,但这是毫无意义的,它不能帮助我们推断屋顶是不是漏水。

Even if a meaningful resolution exists in our problem, it may not be of any use to us. For example, the proposition ‘rain today’ could be resolved into an enumeration of every conceivable trajectory of each individual raindrop; but we do not see how this could help a meteorologist trying to forecast rain. In real problems, there is a natural end to this resolving, beyond which it serves no purpose and degenerates into an empty formal exercise. We shall give an explicit demonstration of this later (Chapter 8), in the scenario of ‘Sam’s broken thermometer’: does the exact way in which it broke matter for the conclusions that Sam should draw from his corrupted data?

即使我们的问题中存在有意义的分解方案,它也可能对我们也没有任何用处。例如,“今天下雨”的命题可以分解为每个雨滴的每个可能的轨迹;但是我们没有看到这对气象学家如何预测降雨有何帮助。在真正的问题中,这种对问题的分解过程自然会有个终点,越过这个终点,分解就失去了意义,退化成一个空洞的形式化的练习。在后面(第8章中)的“山姆的坏掉的温度计”将明确的展示这一点：温度计到底是如何损坏的,对于山姆从错误的温度值中得出的结论有什么影响吗?

In some cases there is a resolution so relevant to the context of the problem that it becomes a useful calculational device; Eq. (2.98) was a trivial example. We shall be glad to take advantage of this whenever we can, but we cannot expect it in general. Even when both A and B can be resolved in a way meaningful and useful in our problem, it would seldom be the case that they are resolvable into the same set of elementary propositions $$ω_i$$ . And we always reserve the right to enlarge our context by introducing more propositions D, E, F, . . . into the discussion; and we could hardly ever expect that all of them would continue to be expressible as disjunctions of the same original set of elementary propositions $$ω_i$$ . To assume this would be to place a quite unnecessary restriction on the generality of our theory.

在某些问题中,某个分解方式恰好和上下文有关,所以可以成为一个有效的计算方式,(2.98)就是一个例子。只要可能,我们很乐意利用这种方法,但我们不能指望它广泛存在。即使A和B都在问题中都能找到某个有意义且有效的分解方式,但不大可能它们可以分解为同一组基本命题$$ω_i$$。我们期望在讨论问题的时候,总是可以引入更多命题,如D,E,F等等来扩充问题的,而且我们很难指望这些新命题也可以通过组合同一组原始基本命题$$ω_i$$来表示。如果要求上面这些都成立,将对我们理论的普遍性施加一个非常不必要的限制。

Therefore, the conjunction AB should be regarded simply as the statement that both A and B are true; it is a mistake to try to read any more detailed meaning, such as an intersection of sets, into it in every problem. Then p(AB|C) should also be regarded as an elementary quantity in its own right, not necessarily resolvable into a sum of still more elementary ones (although if it is so resolvable this may be a good way of calculating it). We have adhered to the original notation A + B, AB of Boole, instead of the more common A ∨ B, A ∧ B, or A ∪ B, A ∩ B, which everyone associates with a set theory context, in order to head off this confusion as much as possible.

因此,逻辑交AB应简单地视为A和B都为真的陈述,在所有问题中试图对此挖掘出更多的含义都是错误的,例如视为对集合求交集。所以p(AB|C)本身应该被看成就是一个数值,没必要将其解析为是多个基本元素之和(即使存在这种解析时,这可能是更好的计算方法)。我们有必要遵循乔治.布尔的原始符号,A+B和AB,而不是更常见的A∨B,A∧B,或A∪B,A∩B,这让人总是联想到集合论,把人引向更多的混乱。

So, rather than saying that the Venn diagram justifies or explains (2.104), we prefer to say that (2.104) explains and justifies the Venn diagram, in one special case. But the Venn diagram has played a major role in the history of probability theory, as we note next.

因此,与其说维恩图证实或解释了(2.104),不如说(2.104)在一个特例中解释并证明了维恩图。但维恩图在概率论的历史曾扮演了了重要角色,正如我们下面会见到的。

3 A physicist refuses to call them ‘atomic’ propositions, for obvious reasons.

注3 由于显而易见的原因,物理学家拒绝称他们为“原子”命题。

=== 2.6.4 柯尔莫哥洛夫公理

In 1933, A. N. Kolmogorov presented an approach to probability theory phrased in the language of set theory and measure theory (Kolmogorov, 1933). This language was just then becoming so fashionable that today many mathematical results are named, not for the discoverer, but for the one who first restated them in that language. For example, in the theory of continuous groups the term ‘Hurwitz invariant integral’ disappeared, to be replaced by ‘Haar measure’. Because of this custom, some modern works – particularly by mathematicians – can give one the impression that probability theory started with Kolmogorov.

1933年,A.N。Kolmogorov提出了一种用集合论和测度论(Kolmogorov,1933)的语言来表述概率论的方法。这种方式刚刚变得如此流行,以至于今天许多数学结果不是用发现者来命名,而是用那些首先用这种语言重新表述述的人来命名。例如,在连续群理论中,“Hurwitz不变积分”一词消失了,取而代之的是“Haar测度”。由于这种习俗,一些著述--尤其是数学家的--给人一种感觉,好像概率论从科尔莫戈罗夫开始。

Kolmogorov formalized and axiomatized the picture suggested by the Venn diagram, which we have just described. At first glance, this system appears so totally different from ours that some discussion is needed to see the close relationship between them. In Appendix A we describe the Kolmogorov system and show that, for all practical purposes, the four axioms concerning his probability measure, first stated arbitrarily (for which Kolmogorov has been criticized), have all been derived in this chapter as necessary to meet our consistency requirements. As a result, we shall find ourselves defending Kolmogorov against his critics on many technical points. The reader who first learned probability theory on the Kolmogorov basis is urged to read Appendix A at this point.

Kolmogorov对我们刚才描述的维恩图所暗示的景象进行了形式化和公理化。乍一看,这个系统看起来与我们完全不同,需要进行一些讨论才能看出它们之间的密切关系。在附录A中,我们描述了Kolmogorov系统并且表明,出于所有实际目的,关于他的概率测度的四个公理,其最早表述的有点武断(Kolmogorov因此被指责了),在本章中为了满足一致性要求,都已经被推导出来了。作为结果,针对这些批评,我们在许多技术问题上捍卫Kolmogorov的观点。那些一开始就学习的是基于Kolmogorov的概率论的读者,建议现在阅读一下附录A.

Our system of probability, however, differs conceptually from that of Kolmogorov in that we do not interpret propositions in terms of sets, but we do interpret probability distributions as carriers of incomplete information. Partly as a result, our system has analytical resources not present at all in theKolmogorov system. This enables us to formulate and solve many problems – particularly the so-called ‘ill posed’ problems and ‘generalized inverse’ problems – that would be considered outside the scope of probability theory according to the Kolmogorov system. These problems are just the ones of greatest interest in current applications.

然而,我们的概率系统在概念上与Kolmogorov不同,因为我们不用集合来解释命题,而将概率分布解释为不完整信息的载体。部分结果是,我们的系统拥有一些在科尔莫戈罗夫系统中根本不存在的分析手段。这使我们能够形式化并解决许多问题--特别是所谓的“病态”问题和“广义否”问题--根据Kolmogorov系统,这些问题将被认为超出了概率论的范围。这些问题正是目前应用中最受关注的问题。
