== 2.2 逻辑和的规则

由于目前考虑的都是亚里士多德式逻辑的命题，只能为真或假，所以逻辑乘$$A\bar{A}$$永为假，逻辑和$$A+\bar{A}$$永为真。A为假的似真度必须以某种方式依赖于A为真的似真度。如果我们定义u≡w(A|B),v≡w($$\bar{A}$$|B)，则必然存在一个的函数关系：

 v=S(u).           (2.36)

显然，为了和常识保持定性上的一致，需要S(u)在0≤u≤1上是连续的单调递减函数，而且其极值满足S(0)=1，S(1)=0。但仅仅满足这些属性的任意函数还不够，它必须与乘积规则一致,即可以被写为AB或$$A\bar{B}$$两者之一:

 $$ w(AB|C)=w(A|C)w(B|AC) $$  (2.37)
 $$ w(A\bar{B}|C)=w(A|C)w(\bar{B}|AC) $$  (2.38)

于是，利用(2.36)和(2.38)，则(2.37)变为

 $$ w(AB|C)=w(A|C)S[w(\bar{B}|AC)]=w(A|C)S[ {w(A\bar{B}|C) \over w(A|C)} ] $$   (2.39)

再一次使用交换律：w(AB|C)对A和B是对称的，同时还要满足一致性,则有:

 $$ w(A|C)S \Bigl[ {w(A\bar{B}|C) \over w(A|C)} \Bigr] = w(B|C)S \bigl[ {w(B\bar{A}|C) \over w(B|C)} \bigr]$$   (2.40)

这对于所有命题A、B、C必须是成立的。特别的，(2.40)必须成立，当

 $$ \bar{B}=AD $$  (2.41)

其中，D可以是任何新命题。然后，我们得到了之前在(1.13)看到的真值：

 $$ A\bar{B}=\bar{B},   B\bar{A}=\bar{A} $$  (2.42)

并且，在(2.40)中我们可以写出

 $$ w(A\bar{B}|C)=w(\bar{B}|C)=S[w(B|C)] $$  (2.43)
 $$ w(B\bar{A}|C)=w(\bar{A}|C)=S[w(A|C)] $$

因此，使用缩写

 $$ x \equiv w(A|C), y \equiv w(B|C) $$  (2.44)

(2.25)变成函数方程:

 $$ xS[ {S(y) \over x} ]=yS[ {S(x) \over y} ], 0 \le S(y) \le x, 0 \le x \le 1 $$  (2.45)

这说明如果要求S(x)符合积规则,必须具有比例性质。在y=1特殊情况下，这将简化为

 $$ S[S(x)]=x $$  (2.46)

该式表明S(x)是一个自反函数，$$S(x)=S^{-1}(x)$$。于是，从(2.36)可得到u=S(v)。但这只是说明了一个事实,A和$$\bar{A}$$是互补关系。这两个命题,哪个用字母表示,哪个用字母上加横线表示,都无所谓。我们在(1.8)之前就看到了这点，即使之前没注意到,现在也必须看出来了。

在(2.45)中给出的定义域如下。D是任意命题，无论D为何，w(D|AC)的值的范围是:

 $$ 0 \le w(D|AC) \le 1 $$  (2.47)

由于S(y)=w(AD|C)=w(A|C)w(D|AC)，并且(2.47)就是(0≤S(y)≤x)，正如在(2.45)里所述。x和y的值域是对等的,可以随意交换。在几何上，在xy平面上,在单位正方形（0≤x，y≤1）之内,曲面y=S(x)本身和之上的所有点所组成。

事实上，该曲线的形状已经由位于(2.45)上方且无限接近的点所确定。因为,假设设定$$y=S(x)+\epsilon$$，那么当$$\epsilon \to 0^+$$时，(2.45)中的两项趋于S(1)=0，但速率不同。所以一切都和$$S(1-\delta)$$一样,在$$\delta \to 0$$时趋近于零。为了探讨这一点，我们定义一个新变量q(x,y)，该变量满足

 $$ {S(x) \over y} = 1-exp \{-q \} $$  (2.48)

选择$$\delta =exp{-q}$$，定义函数J(q)如下

 $$ S(1- \delta )=S(1-exp \{ -q \} = exp \{-J(q)\} $$  (2.49)

可以看到渐进趋势是$$q \to \infty$$。

现在考虑x,q都是独立变量，由(2.48)得到

 $$ S(y)=S[S(x)]+exp \{ -q \} S(x) S^` [S(x)] + O(exp \{ -2q \}) $$  (2.50)

用(2.46)和它微分S"[S(x)]S'(x)=1，可以简化为

 $$ {S(y) \over x} = 1 - exp \{ -( \alpha + q) \} + O(exp \{ -2q \} ) $$  (2.51)

其中

 $$ \alpha (x) \equiv log [ {-xS^` (x) \over S(x) } ] > 0 $$  (2.52)

用这些进行替代后，我们的函数方程(2.45)变为

 $$ J(q+ \alpha) -J(q) = log[ {x \over S(x)} ] + log(1-exp \{-q \} ) + O(exp \{ -2q \} ), 0<q< \infty, 0<x \le 1  $$  (2.53)

当时$$q \to \infty$$，后两项以指数级别趋于零，所以J(q)一定是逐步趋近于线性，

 $$ J(q) \sim \alpha +bq+O(exp \{ -q \} ) $$  (2.54)

且斜率为正

 $$ b= \alpha^{-1} log[{x \over S(x)}] $$  (2.55)

在(2.54)中，没有一个周期项的周期为$$\alpha$$，因为对于x的不同取值,(2.53)必须保证连续,同样对于连续的$$\alpha (x)$$值(2.53)也必须保持连续。但是，因为J被定义为只是关于q的方程，所以(2.55)等式右边必须独立于x。用(2.52)得到

 $$ {x \over S(x)} = [{-xS^`(x) \over S(x)}]^b, 0<b<\infty $$  (2.56)

或者，重新整理，S(x)必须满足微分方程

 $$ S^{m-1}dS + x^{m-1}dx=0, $$  (2.57)

其中，$$m\equiv 1/b$$是某一为正的常数。满足S(0)=1的唯一解是

 $$ S(x)=(1-x^m)^{1/m}, 0 \le x \le 1, 0<m< \infty $$  (2.58)

反之我们可以立即验证出(2.58)是(2.45)的一个解。

结果(2.58)最先是由R.T.Cox(1946)得到的,其证明和上面不一样,他假设了S(x)可二次可导。之后,Acz´el (1966)也得到了同样的结果,但不需要可导这个条件。（但对现在的应用,可导这个假设对于我们来说是一个无害的前提，因为如果函数方程的解是个不可导函数的话，我们该拒绝整个理论，因为它从定性上与常识相违背。）在任何情况下，(2.58)是满足方程(2.45)和左边界条件S(0)=1的最一般的函数，同时我们发现它自动满足右边界条件S(1)=0。

由于在推导函数等式(2.45)时要求B要满足(2.41)，所以目前我们只是得出,(2.58)只是满足一般一致性要求(2.40)的必要条件。为了检验它的充分性，把(2.58)代入(2.40)，利用了(2.28)和(2.38)我们得到

 $$ w^m(A|C)-w^m(A\bar{B}|C)=w^m(B|C)-w^m(B\bar{A}|C), $$  (2.59)

一个平凡的等式。所以，从(2.40)的意义看，(2.58)是在S(x)上一致性的必要充分条件。

至此的结果可以被总结如下。逻辑积的结合律要求x=A|B的似真度的单调函数w(x)必须遵循乘积规则(2.28)。结果(2.58)表明同样的函数必须也满足和准则

 $$ w^m(A|B)+w^m(\bar{A}|B)=1 $$  (2.60)

其中m为正。当然，乘积规则本身也可以被等价的写为

 $$ w^m(AB|C)=w^m(A|c)w^m(B|AC)=w^m(B|C)w^m(A|BC), $$  (2.61)

于是我们会看到m的值确实是无关紧要的，不管取值为什么，我们都可以定义一个新函数

 $$ p(x) \equiv w^m(x), $$  (2.62)

并且我们规则可以采取形式

 $$ p(AB|C)=p(A|C)p(B|AC)=p(B|C)p(A|BC), $$  (2.63)
 $$ p(A|B)+p(\bar{A}|B)=1 $$     (2.64)

实际上，这没有失去一般性，因为对函数w(x)的唯一要求是单调连续增加,范围从w=0表示不可能到w=1表示决定肯定。但是如果w(x)满足这个条件，那么$$w^m(x)$$，$$0<m<\infty$$也同样满足。所以，因为w(x)是任意的,而m是任意值并没有带给我们额外的好处。基础原理所允许的所有可能性都已经被包含在(2.63)和(2.64)之中，其中p(x)是在范围0≤p(x)≤1内的任意连续单调递增函数。

为了得到似真推理的完备的规则集,即从$$(A_1,...,A_n$$的似真度得出任意逻辑函数$$f(A_1,...,A_n)$$的似真度,是否还需要考虑更多的关系？在乘积规则(2.63)与和规则(2.64)中，我们已经得到了逻辑与命题AB和逆命题$$\bar{A}$$的似真度公式。但是在(1.23)后的讨论中我们注意到，逻辑与和逻辑反构成了完备的运算集,可以导出所有的逻辑函数。

因此，有人会认为确定基本规则的过程可以结束了,通过反复的应用逻辑乘法和加法,应该就可以求出从$$\{A_1,...,A_n\}$$产生的布尔代数的任何命题的似真度。

为了验证这一点，我们先来找到逻辑和A+B的公式。反复应用积规则与和规则，我们有

 $$ p(A+B|C)=1-p(\bar{AB}|C)=1-p(\bar{A}|C)p(\bar{B}|\bar{A}C) $$  (2.65)
 $$ =1-p(\bar{A}|C)[1-p(B|\bar{A}C)]=p(A|C)+p(\bar{A}B|C) $$
 $$ =p(A|C)+p(B|C)p(\bar{a}|BC)=p(A|C)+p(B|C)[1-p(A|BC)] $$

最后得到

 $$ p(A+B|C)=p(A|C)+p(B|C)-p(AB|C) $$  (2.66)

这个通用的和规则是应用中用的最多的一个。明显的，基本的和规则(2.64)是(2.66)的特殊形式，如果令$$B=\bar{A}$$。

 练习2.1 是否能从积规则与和规则出发，对p(C|A+B)找到类似(2.66)的通用公式呢？如果可以，请给出推导；如果不可以，解释为什么？

 练习2.2 现在假设我们有一个基于信息X的命题集合$$\{A_1,...,A_n\}$$，各个命题是相互独立的：$$p(A_iA_j|X)=p(A_i|X)\delta _{ij}$$。证明$$p(C|A_1+A_2+...+A_nX)$$是各个似真度$$p(C|A_iX)$$的加权平均值：
 $$ p(C|(A_1+ ... + A_nX)=p(C|A_1X + A_2X + ... + A_nX) = { \sum_i p(A_i|X)p(C|A_iX) \over \sum_i p(A_i|X) } $$  (2.67)

为了推广结果(2.66)，注意到在(1.17)之后,除了最平凡的逻辑否,任何其他的逻辑函数都可以表达为规范的析取形式，就如(1.17)中对基本逻辑与命题进行求和一样。现在任何一个基本逻辑与命题$${Q_i, 1\le i \le 2^n }$$的似真度,都可由反复应用乘法规则来得到，然后再反复应用(2.66)可以可以得到任何对$$Q_i$$的逻辑和的似真度。实际上，这些基本逻辑与命题彼此互不相交，所以我们发现（见下文(2.85)）这些可以归结为简单的对最多$$(2^n-1)$$项进行求和$$\sum_i p(Q_i|C)$$。

所以，就如并和逆是演绎逻辑的运算符完备集合，在下面的场景中,上面提到的和规则与积规则也构成了是合情推理的完备集合。只要是背景信息可以的确定所有基本与命题的似真度，我们的规则就足以确定从$$\{A_1,...,A_n\}$$产生的布尔代数中的所有命题的似真度。因此,在n=4的情形下，我们需要知道$$2^4=16$$个基本与命题的似真度，然后应用上面的规则就可以确定$$2^{16}=65536$$个布尔代数中的命题的似真度。

但是，这几乎总是超出了实际应用所需要的。如果背景信息足以来确定一小部分基本与命题的似真度，可能就足以我们所关心的那一小部分布尔代数了。

