= 4 Elementary hypothesis testing 初步的假设检验

 I conceive the mind as amoving thing, and arguments as the motive forces driving it in one direction or the other.
 John Craig (1699)


 我认为心灵是令人振奋的东西，而论证是将动力推向一个方向或另一个方向的动力。
 约翰克雷格（1699）

John Craig was a Scottish mathematician, and one of the first scholars to recognize the merit in Isaac Newton’s new invention of ‘the calculus’. The above sentence, written some 300 years ago in one of the early attempts to create a mathematical model of reasoning, requires changing by only one word in order to describe our present attitude.We would like to think that our minds are swayed not by arguments, but by evidence. And if fallible humans do not always achieve this objectivity, our desiderata were chosen with the aim of achieving it in our robot. Therefore to see how our robot’s mind is ‘driven in one direction or the other’ by newevidence, we examine some applications that, although simple mathematically, have proved to have practical importance in several different fields.

约翰克雷格是一位苏格兰数学家，也是最早认识艾萨克牛顿新发明的“微积分”的学者之一。上述句子是在大约300年前的早期尝试之一中创建的一种推理的数学模型，为了描述我们目前的态度，只需要用一个词来改变。我们想要认为我们的思想不受论据的影响。 ，但通过证据。如果错误的人类并不总能实现这种客观性，那么我们的选择就是为了在机器人中实现这一目标。因此，为了了解我们的机器人的思维是如何被“一个方向或另一个方向”驱动的，我们研究了一些应用，尽管这些应用在数学上已经证明在几个不同的领域具有实际重要性。

As is clear from the basic desiderata listed in Chapter 1, the fundamental principle underlying all probabilistic inference is:

从第1章中列出的基本要求可以清楚地看出，所有概率推理的基本原理是：

To form a judgment about the likely truth or falsity of any proposition A, the correct procedure is to calculate the probability that A is true:

要对任何命题A的可能真实性或虚假性做出判断，正确的程序是计算A为真的概率：

$$P(A|E_1E_2···)$$ (4.1)

conditional on all the evidence at hand.

以所有手头的证据为条件。

In a sampling context (i.e. when A stands for some data set), this principle has seemed obvious to everybody from the start. We used it implicitly throughout Chapter 3 without feeling any need to state it explicitly. But when we turn to a more general context, the principle needs to be stressed because it has not been obvious to all workers (as we shall see repeatedly in later chapters).

在采样环境中（即当A代表某些数据集时），这个原则从一开始就对每个人都是显而易见的。 我们在第3章中隐含地使用它，而不需要明确说明它。 但是当我们转向更一般的背景时，需要强调这一原则，因为它对所有工人来说并不明显（我们将在后面的章节中反复讨论）。

The essence of ‘honesty’ or ‘objectivity’ demands that we take into account all the evidence we have, not just some arbitrarily chosen subset of it. Any such choice would amount either to ignoring evidence that we have, or presuming evidence that we do not have. This leads us to recognize at the outset that some information is always available to the robot.

“诚实”或“客观”的本质要求我们考虑到我们拥有的所有证据，而不仅仅是一些任意选择的子集。 任何这样的选择都要么忽略我们所拥有的证据，要么假定我们没有证据。 这使我们在一开始就认识到机器人始终可以获得一些信息。
