== 4.8 Comments

=== 4.8.1 Etymology

Our opening quotation from John Craig (1699) is from a curious work on the probabilities of historical events, and how they change as the evidence changes. Craig’s work was ridiculed mercilessly in the 19th century; and, indeed, his applications to religious issues do seem weird to us today. But Stigler (1986a) notes that Craig was writing at a time when the term ‘probability’ had not yet settled down to its present technical meaning, as referring to a (0–1) scale; and if we merely interpret Craig’s ‘probability for an hypothesis’ as our log-odds measure (which we have seen to have in some respects a more primitive and intuitive meaning than probability), Craig’s reasoning was actually quite good, and may be regarded as an anticipation of what we have done in this chapter.

Today, the logarithm-of-odds {u = log[p/(1 − p)]} has proved to be such an important quantity that it deserves a shorter name; but we have had trouble finding one. Good (1950) was perhaps the first author to stress its importance in a published work, and he proposed the name lods, but the term has a leaden ring to our ears, as well as a nondescriptive quality, and it has never caught on.

Our same quantity (4.8) was used by Alan Turing and I. J. Good from 1941, in classified cryptographic work in England during World War II. Good (1980) later reminisced about this briefly, and noted that Turing coined the name ‘deciban’ for it. This has not caught on, presumably because nobody today can see any rationale for it.

The present writer, in his lectures of 1955–64 (for example, Jaynes, 1956), proposed the name evidence, which is intuitive and descriptive in the sense that, for given proportions, twice as many data provide twice as much evidence for an hypothesis. This was adopted by Tribus (1969), but it has not caught on either.

More recently, the term logit for U ≡ log[y/(a − y)], where {yi } are some items of data and a is chosen by some convention such as a = 100, has come into use. Likewise, graphs using U for one axis are called logistic. For example, in one commercial software graphics program, an axis on which values of U are plotted is called a ‘logit axis’ and regression on that graph is called ‘logistic regression’. There is at least a mathematical similarity to what we do here, but not any very obvious conceptual relation because U is not a measure of probability. In any event, the term ‘logistic’ had already an established usage dating back to Poincar´e and Peano, as referring to the Russell–Whitehead attempt to reduce all mathematics to logic.3

3 This terminology has a much longer historical basis. Alexander the Great sought to make all countries Greek in character, but he died before completing this goal, with the result that the countries he conquered had some Greek characteristics, but not all of them. So instead of calling them Hellenic, they were called Hellenistic. Thus, logistic implies something that has some properties of logic, but not all of them.

In the face of this confusion, we propose and use the following terminology. Note that we need two terms: the name of the quantity, and the name of the units in which it is measured. For the former we have retained the name evidence, which has at least the merit that it has been defined, and used consistently with the definition, in previously published works. One can then use various different units, with different names. In this chapter we have measured evidence in decibels because of its familiarity to scientists, the ease of finding numerical values, and the connection with the base ten number system which makes the results intuitively clear.

=== 4.8.2 What have we accomplished?

The things which we have done in such a simple way in this chapter have been, in one sense, deceptive. We have had an introduction, in an atmosphere of apparent triviality, into almost every kind of problem that arises in the hypothesis testing business. But do not be deceived by the simplicity of our calculations into thinking that we have not reached the real nontrivial problems of the field. Those problems are only straightforward mathematical generalizations of what we have done here, and mathematically mature readers who have understood this chapter can now solve them for themselves, probably with less effort than it would require to find and understand the solutions available in the literature.

In fact, the methods of solution that we have indicated have far surpassed, in power to yield useful results, the methods available in the conventional non-Bayesian literature of hypothesis testing. To the best of our knowledge, no comprehension of the facts of multiple hypothesis testing, as illustrated in Figure 4.1, can be found in the orthodox literature (which explains why the principles of multiple hypothesis testing have been controversial in that literature). Likewise, our form of solution of the compound hypothesis problem (4.73) will not be found in the ‘orthodox’ literature of the subject.

It was our use of probability theory as logic that has enabled us to do so easily what was impossible for those who thought of probability as a physical phenomenon associated with ‘randomness’. Quite the opposite; we have thought of probability distributions as carriers of information. At the same time, under the protection of Cox’s theorems, we have avoided the inconsistencies and absurdities which are generated inevitably by those who try to deal with the problems of scientific inference by inventing ad hoc devices instead of applying the rules of probability theory. For a devastating criticism of these devices, see the book review by Pratt (1961).

It is not only in hypothesis testing, however, that the foundations of the theory matter for applications. As indicated in Chapter 1 and Appendix A, our formulation was chosen with the aim of giving the theory the widest possible range of useful applications. To drive home how much the scope of solvable problems depends on the chosen foundations, the reader may try Exercise 4.6.

Exercise 4.6. In place of our product and sum rules, Ruelle (1991, p. 17) defines the ‘mathematical presentation’ of probability theory by three basic rules:
 $$p(\bar{A}) = 1 − p(A);$$
 if A and B are mutually exclusive, p(A + B) = p(A) + p(B); (4.75)
 if A and B are independent, p(AB) = p(A)p(B).

Survey the preceding two chapters, and determine how many of the applications that we solved in Chapters 3 and 4 could have been solved by application of these rules.

Hint: If A and B are not independent, is p(AB) determined by them? Is the notion of conditional probability defined? Ruelle makes no distinction between logical and causal independence; he defines ‘independence’ of A and B as meaning: ‘the fact that one is realized has in the average no influence on the realization of the other’. It appears, then, that he would always accept (4.29) for all n.

This exercise makes it clear why conventional expositions do not consider scientific inference to be a part of probability theory. Indeed, orthodox statistical theory is helpless to deal with such problems because, thinking of probability as a physical phenomenon, it recognizes the existence only of sampling probabilities; thus it denies itself the technical tools needed to incorporate prior information, to eliminate nuisance parameters, or to recognize the information contained in a posterior probability. However, even most of the sampling theory results that we derived in Chapter 3 are beyond the scope of the mathematical and conceptual foundation given by Ruelle, as are virtually all of the parameter estimation results to be derived in Chapter 6.

We shall find later that our way of treating compound hypotheses illustrated here also generates automatically the conventional orthodox significance tests or superior ones; and at the same time gives a clear statement of what they are testing and their range of validity, previously lacking in the orthodox literature.

Now that we have seen the beginnings of this situation, before turning to more serious and mathematically more sophisticated problems, we shall relax and amuse ourselves in the next chapter by examining how probability theory as logic can clear up all kinds of weird errors, in the older literature, that arose from very simple misuse of probability theory, but whose consequences were relatively trivial. In Chapters 15 and 17 we consider some more complicated and serious errors that are causing major confusion in the current literature.
