== 1.8 评论

政治家们，广告商,销售人员,还有各种以宣传为主要目的的职业,例如政治，经济，道德，宗教，心理，环境，饮食和艺术教条等等，这些人都很清楚，人类的大脑是多么容易被晦涩的言辞所迷惑,完全没注意到这些言辞已经违背了基本原理(上面提到的基础公理).所以我们将尽全力确保我们的机器人不会犯同样的错误。

我们强调机器人和人脑之间的另一个对比。根据基础公理I，在机器人的思维状态中,任何命题都被表示为一个一个实数。现在我们已经了解,我们对一个命题的态度可能有多个“维度”。你我在判断一个命题时，不只判断它似真度是多少，还会判断它是否值有意义,是否重要，是否有用处，是否有价值，是否吸引人，是否合乎道德等等。如果假设每个判断都可以用数字来表示，那么对一个人类思维状态的完整描述,应该用一个多维空间中的向量来表示。

并不是所有的命题都需要这个。例如，“水的折射率小于1.3”这个命题不会产生任何情绪，因此它所产生的精神状态具有很少的维度。另一方面，“你婆婆刚才弄坏了你的新车”这个命题会会让你的大脑在多个维度上产生变化。一般来说，日常生活的情况都会涉及很多维度的情况。正是由于这个原因，我们认为最常见的心理活动往往是最难以建模的。也许正式如此我们都认为，科学和数学是人类活动中最成功的原因：它们处理的命题引起的精神状态是最简单的。这种状态是人类头脑中因为大脑的不完美因素受到扰动最小的状态。

当然，因为许多原因，我们不希望我们的机器人去考虑这些“人”的特征而增加的额外维度。电脑不会被情绪而困扰，不会因为问题的复杂而感到厌倦，也不会去猜测那些隐含的动机，这使得它们在执行某些任务时比人更可靠。

插入上面的言论是为了指出，本书试图研究的理论,将其泛化或扩展的领域是巨大的,可能会激励他人尝试开发出一个思维活动的“多维理论”，使得这种理论更接近人类的大脑 - 除去那些是我们不想拥有的特质。这样一个理论，如果成功的话，可能会超出我们现在的想象能力。

但是，现在我们不得不满足于一个更为适中的任务。是否能建立一个一致的“一维”的似真推理模型？显然，问题会变得十分简单,如果我们只用一个实数来表示似真度，而忽略刚才提到的其他“维度”。

我们要强调一下,从任何角度来看，我们不认为在人脑中似真度真的对应一个数值。我们的工作不是假设-或者甚至是猜测-这类问题,而是研究是否可能,在机器人中建立这种对应而不产生矛盾。

但对某些人来说，似乎我们的某些假设是不必要的，从而限制了理论的普遍性。为什么必须用实数表示似真度？是否只要满足(A|C)>(B|C)这样的有序集就够了?附录A中，描述了一些其他方式的概率论，有一些尝试仅使用有序关系来研究，因为这样可能简化逻辑或者更通用。但这并未奏效,即使方式和我们的不同,但最后的结果是一样的。

注5: 事实上，一些心理学家认为只要五个维度就足以描述人的个性;也就是说，我们所有人的差异只在于五种基本人格特质的不同组合，而这五种特质可能是基因决定的。但在我们看来，这显然是过分简化了。在空间和时间上不断变化的会影响思维活动的,可识别的化学因素（例如脑中葡萄糖代谢的分布），不可能忠实的表示在五维空间中。然而，也许对于很多情况来说,五个维度可能足够了.

== 1.8.1 普通语言和形式逻辑

我们应该注意形式逻辑和普通语言在表述上的区别。有人认为普通语言只是表达形式不那么准确而已,但是考察细节后两者显然不止如此。我们发现，仔细小心的使用普通语言没有比形式逻辑不精确,只是普通语言的语法更加复杂，导致了更加丰富多变的表达方式,远多过形式逻辑所允许的。

通用语言特别的，被用在逻辑以外的很多领域中，已经发展出了微妙的差别 - 暗示但不明确说出来 - 这种差别形式逻辑中被忽略了。A先生想肯定他的观点说：“我相信我看到的。”B先生反驳道：“他没看到他不相信的。”从形式逻辑的角度来看，他们说的是一回事;但从通用语言的角度来看，它们表达了完全相反的意思。

下面是一个稍微复杂的例子，取自数学教科书。设L是平面上的一条直线，S是该平面上的无限点集，每个点都被影射到L上。现在考虑以下陈述：

 (I) 极限的影射是影射的极限.
 (II) 影射的极限是极限的影射.

两者有同样的语法结构‘A是B’和‘B是A’,所以它们看起来是逻辑等价的.但是在那本书中,(I)总为真而(II)通常为假,因为当集合的极限不存在的情况下,可能存在影射的极限.

正如我们所看到的，用通用的语言 - 甚至在数学教科书中 - 虽然我们已经学会分辨语句的细微差别，但就像上面例子一样,在差别被指出之前我们都没有意识到这个差别。对于“A是B”,我们首先认为这是一个判定,大前提是A存在，剩下的被理解为在这个前提的条件下。换句话说，在普通语法中，动词“是”意味着区分了主语和宾语,而两者是不完全相同的，而符号“=”在形式逻辑或传统数学中没有有这个意味。（然而，在计算机语言中，我们会看到类似'J=J+1'这样的语句而且谁都看得懂,在这里'='号就暗示了"不同"的意思。)

另一个有趣的例子是古老的格言“知识就是力量”，这是显而易见的事实，无论是在人际关系还是热力学中。一位化学商业杂志的广告作者,无耻的写成“权力就是知识”，真是荒谬而且讨厌的错误。

这些例子提醒我们，动词“是”和其他任何动词一样，有一个主语和一个谓语;但很少注意到这个动词有两个完全不同的含义。一个母语是英语的人可能费点力气才能意思到下面​​陈述中的不同含义：“房间真是很吵”和“房间里净是噪音”。但在土耳其语中，这两个意思是用不同的词来表达的，使得这种区别如此显而易见,如果你用错了词,别人会听不懂.后一种说法是本体论的，主张某种东西的物理存在，而前者是认识论的，只表达说话者的个人感知。

通用的语言,或者至少是英语,有一个普遍的倾向,用一种接近表述客观存在的语法形式来表达一个主观认知的句子,常常让那些麻痹大意的人上当。这是当前概率论的一个主要的错误来源,尤其是在没有经过缜密思考的时候。以客观存在的角度来解释一个句子时,是在断言一个人的想法和感受就是外在的,自然的现实存在。我们称之为“思维影射谬误”，以及随之而来的诸多问题和麻烦。但是这个问题并不局限于概率论，一旦被指出就会显而易见，那些哲学家和格式塔心理学家的许多话语,以及物理学家解释量子理论的尝试，由于作者反复的"思维影射错误"而使得这些工作变得毫无意义。

注6 LC-CG Magazine, March 1988, p. 211.

这些例子说明了当我们试图将通用语言的复杂句子翻译成形式逻辑的简单陈述时需要多么谨慎。当然通用语言往往不如我们要求形式逻辑的那么精确。但是大家知晓这点并且谨慎处理，那么它也就不那么危险了。

期望我们的机器人能够掌握需要一个人花费20年时间学习才能识别的通用语言中的细微差别的能力，实在太难了。在这方面，我们只期望机器人只要像一个小孩就够了 - 仅从字面上理解句子，而不用考虑会不会冒犯别人。

作者也不清楚这有多困难,以及有多大必要,设计一个新型机器人,能够识别这些细微又模糊的差异。当然，既然人脑可以做到,这个原则问题是不可避免的。不过在实践中，可以适用冯·诺依曼原理:直到有人发展出"差异认知”理论,把认知过程归结成明确定义的一系列操作,我们才能设计出这样的机器人。我们很乐意将此留待别人完成。

无论如何，我们现在的机器人模型是确实存在的，因为今天几乎所有稍微复杂的概率计算都是在计算机上执行的。在计算机上编程的这个人，无论他们是否这样想，都必然是根据先入为主的一些机器人应该如何工作的概念来设计机器人的部分"大脑"。但现在使用的程序中只有很少一些能满足我们所有的基本原理,事实上，大多数都是出于直觉的,没有基于任何恰当的原则而设计出来的专用程序。

这些专用程序适用于某些特定的应用领域,这正是选择它们的原因,但是正如第2章的证明所显示的那样，这些与概率论的规则有冲突的特定手段,在其适用领域之外,必然会展现出明显的不一致的情况。我们的目的是一次的,一劳永逸的,满足一致性的要求,一充分无二义的形式，发展出通用的推理原则,以避免上述情况。

== 1.8.2 吹毛求疵

从上面可以明显看出，目前位置我们使用术语“布尔代数”的本来意义,即用符号“A”代表命题的二值逻辑。一些有强迫症的人会对此吹毛求疵，说一些数学家对这个术语的含义略的使用有不同，'A'可以指一类命题。但两种用法并不冲突，我们承认其更广泛的含义，只是我们用不到而已。

我们称之为“布尔代数”的一套规则和符号有时也被称为“命题演算”。使用这个术语的时候,似乎主要想说我们还需要另一套叫做“谓词演算”的规则和符号。然而这些新的术语被证明只是对已经熟悉的一些短语的缩写。“通用量词”就是“所有”的缩写,“存在量词”是“有一个”的缩写。如果用普通英语来写陈述语句，我们自然而然的使用所有的必要的谓词演算，而且可易于理解。

有时,第二个强三段论（二值逻辑）的有效性会受到质疑。不过在现今的数学中，通过一个反例来否定一个假象理论仍然是一个合法的推理手段，即一组陈述被认为是不一致的如果能够从中推出一个矛盾，而且也可以通过反证来证明一个命题，即从否命题中推出矛盾。这些方法对我们来说已经足够了。我们很乐于遵循这些悠久传统。我们的安全感来源于这样的信念，逻辑学可以继续发展演进，但它绝不会倒退。新的逻辑学可能得出亚里士多德逻辑学中从未考虑过的东西,事实上这正是我们现在正在努力在做的。但是当然，如果在亚里士多德逻辑适用的领域发现新的逻辑与亚里士多德逻辑相冲突，那么我们就会认为这是对新逻辑的一个致命的反对理由。

因此，对那些感觉到被二值演绎逻辑限制的人来说，我们只能说：“如果你愿意的话，可以调查其他的可能性;如果你找到一个没有包含在二值逻辑和我们的扩展的逻辑中的新结果，并且对科学推理有用，那么请告诉我们.实际上现有文献中存在着许多,不同的且互不兼容的多元逻辑理论。但是在附录A中，我们提出了一些论点，认为它们提供在二值逻辑之外更有用的内容,也就是说，应用于一组命题的n值逻辑要么等同于应用于扩大集的二值逻辑，要么包含内部不一致。

我们的经验是符合这个猜想的;在实践中，多值逻辑的主要用处不是用来找到新结果，而是试图消除使用二值逻辑所带来的麻烦，特别是在量子理论，模糊集合和人工智能方面。不过只要仔细研究一下，我们会发现所有这些困难，可被证明都是某种思维影射谬误，与其说是新的逻辑还不如直接修正某些概念。

