== 1.3 思考的机器

不同的模型可能有完全不同的实际用途。 很多人都喜欢说：“他们永远无法用一台机器来替代人的思考,人做的很多事情是机器无法做到的”。冯·诺依曼（J. von Neumann）在一个关于计算机的讨论会(1948年,普林斯顿，作者有幸参加)中给出了一个完美的回答。 在听众提出这个经典问题（显然机器不可能会思考，难道不是吗？”）时,他说：

你坚持认为有些事情是机器做不到的。但只要你能精确地告诉我机器什么不能做，那我就可以制造一台机器做到它！

原理上，机器不能为我们执行的唯一操作就是我们无法详细描述所有细节的操作，或者无法在有限次的步骤中完成的操作。 当然，有些人会想到哥德尔不完备定理，图灵机的停机问题等等。但是要回答所有这些怀疑，我们只需要指出能"做到"这些的现实存在--人脑! 就像冯·诺伊曼所指出的那样，制造“思考机器”的唯一限制是我们自己的局限性:我们不知道到底是什么构成了“思维”。

但是，在我们对常识的研究中，我们可以看出一些关于思考机制的非常显而易见的观点。 每一次我们通过定义一组操作来构建一个数学模型，一个可以再现常识的一个部分的模型.参照这个过程,我们就能“建造一台机器”（例如编写一个计算机程序），它基于不完整的信息上并应用上述弱三段论的量化过程来运行，使用合情推理并不是演绎推理而得出结果。

事实上，针对某些特定的推理问题,开发解决此问题的计算机软件是当前这一领域最活跃和最有用的趋势之一。 这种问题的一个例子可能是：给定大量(包括10 000个独立的观测的)数据，从这些数据和现有的先验信息,来估算可能影响了结果的100种不同原因的相对可信度。

应用独立的常识我们就足以决定导致不同后果的两个假设之中该如何抉择;但是在面对100个有细微区别的假设时，如果不借助于计算机和指导如何编程的数学理论，我们几乎就是束手无策了。也就是说，在警察的三段论（1.5）中，究竟是A的合理性增加足够多以至于接近于100%肯定,还是由于B的合理性减少的足够小使得B可以忽略不计？本书的目的就是要发展一个数学理论来回答这样的问题，尽可能的使其具有足够的深度和通用性。

虽然我们希望找到一个能够用于计算机编程的数学理论，但会思考的计算机的这个想法,在心理学上也有助于发现这样的数学理论。问题是人脑的真实推理过程中的充满了情感和怪诞的误解。只要谈到这个问题,就无法不涉及一些和我们的目标无关的争论,即我们已经掌握的知识是不是足以解决这个问题?

显然，真正的人类大脑的运作是如此复杂，以至于我们不能解释它的奥秘。在任何情况下，我们都不想解释，更不用说重现人类大脑的所有偏差和不一致。这是一个有趣而重要的课题,但这不是我们在这里研究的课题。我们的话题是正规化的逻辑原理，而不是心理学或神经生理学的原理。

为了强调这一点，我们不要问“如何建立一个人类常识的数学模型？”,而是要问"如何构建一个机器,它遵循具有明确定义的能表述理想化常识的原理,又能进行有意义的合情推理？"
