== 1.7 基础原理

对于要被推理的每个命题，我们的机器人必须赋予其一个对可信程度的度量,基于我们提供的事实或证据.每当它得到新证据时，都必须做出评估并对似真度做出修正。在机器人的大脑中,为了能够存储并修改似真度，这些度量必须对应于某种确定的物理量，例如电压大小或脉冲持续时间亦或二进制数值等等,当然这些细节的设计是工程人员的工作。对我们的目的而言，这意味着在可信程度和实数值之间必须存在某种关系：

 (I) 似真度用实数来表示。 （1.28）

因此,基础原理I实际上强制我们:机器人的大脑必须运作在某种确定的物理过程之上。而且这种强制性也来自于理论上（见附录A）.我们看不到有任何可能性,存在一个自洽的理论,具有和基础原理I等价的属性。

我们遵循自然但非必不可少的惯例：更大的似真度应该对应于更大的数。方便起见,我们还假设它具有连续性，虽然现在难以精确地表述这个概念,不过从直觉上可以表达为:无穷小的似真度应该对应无穷小的数。

机器人赋给命题A一个似真度,一般而言依赖于我们告诉它另一个命题B是否为真。我们采用凯恩斯（1921）和考克斯（1961）的符号表示方法:

 A|B,     (1.29)

称为"给定B为真时A为真的条件概率",或给定B时A的条件似真度,用实数表示. 因此例如:

 A|BC     (1.30)

读成"A当给定BC",表示给定B和C都为真时A为真的似真度.或者

 A+B|CD    (1.31)

表示给定C和D都为真时,命题A和B至少有一个为真的似真度,如此等等.我们已经决定用大的数来表示较大的似真度,所以:

 (A|B)>(C|B)   (1.32)

即给定B时,A比C更加可信(似真).此方式下,对A|B这样不带括号的表示方法,为了防止歧义,我们通常会加上括号来明确表示.因此, (1.32) 和下面的是等价的:

 A|B>C|B,     (1.33)

但看起来更明确.

为了避免处理那些不可能为真的问题，我们不会要求我们的机器人承受从不可能的或相互矛盾的前提出发进行推理的痛苦,那不可能得出“正确的”答案。 因此，当B和C相互矛盾时，我们不试图定义A|BC。 只要出现这样的符号，我们假定B和C是相容的命题。

另外，我们不希望这个机器人以一种与你我的思考方式相反的方式思考。 因此，我们将其设计成至少在定性的意义上和人类推理的方式是相似的，正如上述弱三段论和其他相关规则一样。

所以,当旧有信息C被更新为C'时,A的似真度将增加:

 (A|C')>(A|C);  (1.34)

但给定A时A的似真度没有变:

 (B|AC')=(B|AC).  (1.35)

这导致,A和B同时为真的似真度只会增加,而不会减少:

 (AB|C') ≥ (AB|C);  (1.36)

而且A为假的似真度必然减少:

 $$(\bar{A}|C')<(\bar{A}|C)$$   (1.37)

这个定性的要求,简明的指出了机器人推理的前进"方向",没有指出似真度应该改变多少,但连续性假设(为了在定性上和常识保持一致的条件)要求我们,当A|C仅仅有无穷小的改变时,也只导致AB|C和$$\bar{A}|C$$的无穷小的改变.如何应用定性要求的具体方法将在下一章给出,现在只是需要的时候才会提到它.目前为止,上面的总结如下:

 （II）在定性的角度,保持和常识一致。        （1.38）

最后，我们想让我们的机器人拥有另外一个特质，而这一点是一个真诚的人想要保持住却难以保持的特质:即永远保证推理的一致性. 这里我们是指三种常见的语言表达上的"一致性"：

 （IIIa）如果可以以多种推理方式得出一个结论，那么所有方式必须得出相同的结论。（1.39A）

 （IIIb）机器人总是考虑到和问题有关的所有证据。它不应只从"随意"挑选出来的部分证据来得出结论,而忽略其他信息。换句话说，机器人不存在"意识形态"问题。（1.39b）

 （IIIc）机器人总是对相同的认知状态赋予相同的似真度。 也就是说，在推理不同的问题时,机器人的认知状态的是相同的（排除仅仅是命题的表示方式不同），那么在两个问题中它必须对相同的认知赋予相同的似真度。（1.39c）

基础公理I,II和IIIa是我们机器人大脑内部工作的基本“结构”要求，而（IIIb）和（IIIc）是机器人的"接口"条件即其行为如何与外界关联。

大多数学生惊讶地发现，我们定义的基本原则已经到此为止了。 事实证明，上述条件唯一地决定了机器人推理必须遵守的规则,即只存在唯一一组满足上述条件的计算似真度的数学运算。 这些规则在第2章中推导出来。

（在大多数章节的最后，我们插入一段非正式的评论，其中收集了各种各样的旁白，背景材料等等。读者可以跳过它们，而不会失去论证的主线。）

