== 1.1 演绎推理和合情推理

花几秒钟想一下,我们就能知道警察得出结论不是基于对证据的演绎推理, 因为对于任何事情都可以找到一个完美无暇的开脱。 例如，这位先生可能就是这家珠宝店的老板，他刚从一个化妆舞会派对回家并且忘了带钥匙。 当他恰好走过他的珠宝店时，一辆路过的卡车丢出一块石头打破了窗户，于是他不得不保护自己的财产。

现在，虽然警察的推理过程并不合乎逻辑演绎，但我们仍然相信这很是合情合理。 证据并不能证明这位先生一定是个小偷,但看起来这是合情合理的推论。 这种推理的例子,在我们学会数学理论之前,就已经或多或少的熟练运用了。 在我们散步看风景的时候,对有些突发问题(是不是要下雨了),我们没有充分的信息来进行演绎推理，但我们仍然必须快速的做出决定。

尽管这听起来很熟悉，但得出合情结论是一个非常微妙的过程。 尽管对此过程的讨论记载已经延续了24个世纪，看起来还没人能把这个过程分析的让所有人都完全满意。 在本书中，我们将给出一些有用的和令人鼓舞的新进展，其中用明确的定理取代矛盾的直觉，特别是用一些基本的--几乎不可避免的--理性标准来取代特殊解决手法.

所有关于这些问题的讨论都以演绎推理和合理推理之间的对比开始。 一般认为是亚里士多德（约公元前四世纪）([[file:chapter01.org::#footnote1][注1]])最先系统的规范了演绎推理（apodeixis）,将其归结为对两种强三段论的反复运用：

 如果A为真,则B为真
 A为真            (1.1)
 所以B为真

及其逆用:

 如果A为真,则B为真
 B为假                (1.2) 
 所以A为假

这种推理方式是我们最想使用的; 但是，在几乎所有我们遇到的情况中，我们都找不到合适的信息来进行这种推理。 我们只好求助于弱三段论（epagoge）：

 如果A为真,则B为为真
 B为真                (1.3)
 所以,A为真变得更加合情理

证据不足以证明A为是，但A的一个后果为真确实让我们对A有更多的信心。例如:

 A = 最迟在上午10点开始下雨
 B = 上午10点之前天空会变得多云

如果上午9:45观察到天空多云,并不能让我们从逻辑上相信一定会下雨。 然而服从弱三段论的常识，会促使我们改变计划仿佛相信雨一定会下的，只要这些云是足够黑暗。

这个例子还表明“如果A然后B”这个主要前提,只表示B作为A的逻辑结果,而不一定是一种物理意义上的因果关系,B只有在过一段时间后才会生效。 上午十点下雨不是9点45多云的物理意义上的原因.然而正确的逻辑关系应该是确定的非因果顺序的（雨=>云）,而不是不确定的因果顺序的（云=>雨）。

我们首先强调的是，我们在这里关心的只是逻辑关系而不是物理因果.由于没有看出逻辑上的蕴涵关系和物理因果之间的区别,导致一些推理发生了严重的错误。 Simon和Rescher（1966）对这一区别进行了深入的分析，他们指出，所有将蕴含解释为是在表达物理因果的努力,都由于缺少强三段论的逆否形式（1.2）而翻了车。 也就是说，如果我们试图把“A是B的物理上的因”解释为大前提，那么我们就无法同时承认“否B也是否A的物理上的因”。 在第三章中我们将看到，试图从物理因果的角度来解释合情推理同样并不灵光。

同样的大前提,另一种弱三段论是

 如果A为真,则B为真
 A为假       (1.4)
 所以,B为看起来更不合情理一些.

在这种情况下，无法证明B是假的;但是B为真的一个前提条件被排除了,因此我们对于B为真的信心就变弱了一些。一个科学家在思考是接受还是拒绝自己的理论时，几乎全部应用的是弱三段论的第二和第三种形式。

现在看警察的推理过程并不符合上面的任何一个形式,而是更符合下面的更弱一些的三段论形式:

 如果A为真,则B为真的可能性更大
 B为真       (1.5)
 所以A为真的可能性变的更大了

尽管在用抽象的A和B来表达论证过程时,这种方式的证明力看起来太过薄弱，但我们认识到警察的结论具有很强的说服力。 似乎有什么东西让我们相信，在这个特殊情况下警察的论证几乎具同演绎推理的有同样的可信度。

这些例子说明大脑在进行合情推理时，不仅试图判定某事是变得更合情理还是更不合情理，而且以某种方式评估合理的程度。 上午十点有多大可能会下雨很大程度上取决于九点四十五分云层有多黑暗。 在做决定的时候,大脑既使用旧信息也利用新信息,我们试着回忆起我们过去关于云雨相关的经验，还有昨晚的天气预报。

为了说明警察也会利用之前的一般经验，我们只需要改变之前的经历。 假设对于每个警察,这样的事件每晚都发生过几次，而且每次的嫌疑人都是清白无辜的。 那么警察很快就会学会忽略这些微不足道的情况。

因此在面对一个新问题时，我们的推理非常依赖于先验信息来帮助我们评估可信度。 这种推理过程在无意识中几乎是瞬间进行，我们通过称之为常识来隐藏其真正的复杂性。

数学家George Polya（1945，1954）写了三本关于合情推理的书，提出了很多有趣的例子，表明我们在做合情推理时应用了确定的一些规则（虽然他的工作仍然是定性的分析）。 上面的弱三段论出现在他的第三卷。 强烈建议读者阅读Polya的阐述，因为它是这本书中许多思想的最初来源。 我们在下面展示了如何将Polya的原理定量化，从而得到有用的应用。

显然，在上述的演绎推理中,我们可以把（1.1）和（1.2）串起来形成一个链式的推理过程，并且保证结论和前提具有同样的可靠性。对于(1.3)-(1.5)的推理形式，结论的可靠性随着每一次的应用而发生变化。但是在数量上我们会发现，在许多情况下，我们的结论仍然可以接近演绎推理的可靠性（就像警察的例子中我们预期的那样）。Polya表明，即使是一个纯粹的数学家，大部分时间里实际上也在使用这些较弱的推理形式。当然，在发表一个新发现的定理的时候，数学家会努力去找到一个只用强三段论的论证，但在发现新定理的过程中总是会用到弱三段论来进行推理（例如，用类比的方式来猜测结论）。 S. Banach的评论（S. Ulam，1957）引用了同样的观点：

优秀的数学家看到了理论的相似性;伟大的数学家看到了相似性的相似性.

接下来，让我们观察一下这种相似性,在另一个也是基于合情推理的领域。

注1 Today, several different views are held about the exact nature of Aristotle’s contribution. Such issues are irrelevant to our present purpose, but the interested reader may find an extensive discussion of them in Lukasiewicz (1957).

<<footnote1>> 今天，关于亚里士多德贡献的确切性质，有几种不同的观点。但和我们目前的目的无关，有兴趣的读者可以参阅Lukasiewicz（1957）的讨论。
