== 3.2 Logic vs. propensity 逻辑与偏好习性

The results of Section 3.1 present us with a new question. In finding the probability for red at the kth draw, knowledge of what color was found at some earlier draw is clearly relevant because an earlier draw affects the number $$M_k$$ of red balls in the urn for the kth draw. Would knowledge of the color for a later draw be relevant? At first glance, it seems that it could not be, because the result of a later draw cannot influence the value of $$M_k$$ . For example, a well-known exposition of statistical mechanics (Penrose, 1979) takes it as a fundamental axiom that probabilities referring to the present time can depend only on what happened earlier, not on what happens later. The author considers this to be a necessary physical condition of ‘causality’.

第3.1节的结果向我们提出了一个新问题。在确定第k次抽中红球的概率时，需要知道在此之前都取出了那些颜色的球，因为之前的结果决定了在第k次抽取时盒子中剩余红球的数量$$M_k$$。那么在此之后的抽取结果是否也会影响当前抽取的结果呢?乍一看，这似乎不可能，因为之后的抽取结果不可能影响$$M_k$$的值。例如，在一个众所周知的对统计力学论述(Penrose，1979)中将此作为一个基本公理，即当前时间的概率只能取决于先前发生的事情，而不是后来发生的事情。作者认为这是“因果关系”的一个必要的物理条件。

Therefore we stress again, as we did in Chapter 1, that inference is concerned with logical connections, which may or may not correspond to causal physical influences. To show why knowledge of later events is relevant to the probabilities of earlier ones, consider an urn which is known (background information B) to contain only one red and one white ball: N = 2, M = 1. Given only this information, the probability for red on the first draw is $$P(R_1|B) = 1/2$$. But then if the robot learns that red occurs on the second draw, it becomes certain that it did not occur on the first:

因此，正如我们在第1章中所做的那样，我们再次强调，推理关心的是逻辑关系，逻辑关系可以对应一个物理的因果关系,也可以不对应一个物理的因果关系。为了说明为什么关于后发生事件的知识与先发生的事件的概率相关，考虑一个已知的盒子中(背景信息B)只包含一个红色球和一个白球：N = 2，M = 1.在仅给出此信息的情况下，第一次取出红球的概率为$$P(R_1|B)=1/2$$。但是如果机器人了解到在第二次抽出的是红球的情况下，那么它可以确定第一次抽出的不是红球：

 $$P(R_1|R_2B) = 0$$. (3.38)

More generally, the product rule gives us

更一般的说,乘法规则告诉我们

 $$P(R_jR_k|B) = P(R_j|R_kB)P(R_k|B) = P(R_k|R_jB)P(R_j|B)$$. (3.39)

But we have just seen that $$P(R_j|B) = P(R_k|B) = M/N$$ for all j, k, so

但是我们已经看到对于所有的j和k有$$P(R_j|B) = P(R_k|B) = M/N$$,所以

 $$P(R_j|R_kB) = P(R_k|R_jB)$$, all j, k. (3.40)

Probability theory tells us that the results of later draws have precisely the same relevance as do the results of earlier ones! Even though performing the later draw does not physically affect the number $$M_k$$ of red balls in the urn at the kth draw, information about the result of a later draw has the same effect on our state of knowledge about what could have been taken on the kth draw, as does information about an earlier one. This is our second nonobvious symmetry.

概率论告诉我们，后发生的抽取结果与先发生的抽取结果,对当前抽取结果的关系是完全相同的！尽管在第k次抽取之后的抽取不会在物理上影响盒中红球的数量$$ M_k $$，但是关于后发生的抽取结果的信息,和第k次抽取之前的结果的信息,对第k次抽取结果的的知识状态的影响是相同的。这是我们的第二个非显而易见的对称性。

This result will be quite disconcerting to some schools of thought about the ‘meaning of probability’. Although it is generally recognized that logical implication is not the same as physical causation, nevertheless there is a strong inclination to cling to the idea anyway, by trying to interpret a probability P(A|B) as expressing some kind of partial causal influence of B on A. This is evident not only in the aforementioned work of Penrose, but more strikingly in the ‘propensity’ theory of probability expounded by the philosopher Karl Popper.1

这个结果可能让和“概率意义”有关的思想流派感到非常不安。虽然人们普遍认为逻辑上的蕴涵关系与物理上的因果关系并不相同，但人的思维总是自然而然的滑向两者是一回事的想法,即试图将概率P(A|B)解释为B和A之间至少有部分的因果影响。这一点不仅在之前提到的彭罗斯的著作中很明显，而且在哲学家卡尔.波普尔阐述的“偏好性解释”的概率理论中更为明显。

It appears to us that such a relation as (3.40)would be quite inexplicable from a propensity viewpoint, although the simple example (3.38) makes its logical necessity obvious. In any event, the theory of logical inference that we are developing here differs fundamentally, in outlook and in results, from the theory of physical causation envisaged by Penrose and Popper. It is evident that logical inference can be applied in many problems where assumptions of physical causation would not make sense.

在我们看来，从偏好性解释的观点来看(3.40)这样的关系是非常莫名其妙的，尽管简单的例子(3.38)使其逻辑必然性是显而易见的。无论如何，我们在这里发展的逻辑推断理论在观点和结果上都与彭罗斯和波普尔所设想的物理因果理论有着根本的不同。很明显，逻辑推断可以应用于许多问题，在这些问题中物理因果关系的假设是没有意义的。

This does not mean that we are forbidden to introduce the notion of ‘propensity’ or physical causation; the point is rather that logical inference is applicable and useful whether or not a propensity exists. If such a notion (i.e. that some such propensity exists) is formulated as a well-defined hypothesis, then our form of probability theory can analyze its implications. We shall do this in Section 3.10 below. Also, we can test that hypothesis against alternatives in the light of the evidence, just as we can test any well-defined hypothesis. Indeed, one of the most common and important applications of probability theory is to decide whether there is evidence for a causal influence: is a new medicine more effective, or a new engineering design more reliable? Does a new anticrime law reduce the incidence of crime? Our study of hypothesis testing starts in Chapter 4.

这并不意味着我们被禁止引入“偏好性的”或物理因果关系的概念;重点是无论是否"偏好性"是否存在, 逻辑推理是可用的且有用的。如果这样的概念(即存在一些这样的偏好)被形式化为明确定义的假设，那么我们的概率论形式就可以分析其含义。我们将在下面的3.10节中做到这些。此外，我们可以根据证据来检验互相可比较的假设，就像我们可以检验任何明确定义的假设一样。实际上，概率论最常见和最重要的应用之一是判断是否存在能证明因果关系的证据：新药更有效，或新工程设计更可靠？新的防止犯罪的法律是否会降低犯罪率？我们对假设检验的研究从第4章开始。

1 In his presentation at the Ninth Colston Symposium, Popper (1957) describes his propensity interpretation as ‘purely objective’ but avoids the expression ‘physical influence’. Instead, he would say that the probability for a particular face in tossing a die is not a physical property of the die (as Cram´er (1946) insisted), but rather is an objective property of the whole experimental arrangement, the die plus the method of tossing. Of course, that the result of the experiment depends on the entire arrangement and procedure is only a truism. It was stressed repeatedly by Niels Bohr in connection with quantum theory, but presumably no scientist from Galileo on has ever doubted it. However, unless Popper really meant ‘physical influence’, his interpretation would seem to be supernatural rather than objective. In a later article (Popper, 1959) he defines the propensity interpretation more completely; now a propensity is held to be ‘objective’ and ‘physically real’ even when applied to the individual trial. In the following we see by mathematical demonstration some of the logical difficulties that result from a propensity interpretation. Popper complains that in quantum theory one oscillates between ‘... an objective purely statistical interpretation and a subjective interpretation in terms of our incomplete knowledge’, and thinks that the latter is reprehensible and the propensity interpretation avoids any need for it. He could not possibly be more mistaken. In Chapter 9 we answer this in detail at the conceptual level; obviously, incomplete knowledge is the only working material a scientist has! In Chapter 10 we consider the detailed physics of coin tossing, and see just how the method of tossing affects the results by direct physical influence.

注释1:在第九届科尔斯顿研讨会上，波普尔(1957)将他的"偏好性解释"描述为“纯粹客观的”，但避免说成是“物理上的影响”。相反，他会说，掷骰子的概率并不是骰子的物理特性(正如Cram'er(1946)所坚持的那样)，而是整个实验安排的客观属性，骰子和投掷方法。当然，实验的结果取决于整个安排和程序,这只是一个老生常谈。 Niels Bohr在量子理论方面反复强调，但大概伽利略之后的科学家从未怀疑过这点。然而，除非波普尔真的是想表达“物理上的影响”，否则他的解释似乎是超自然的而不是客观的。在后来的文章(Popper，1959)中，他更完整地定义了偏好性解释;现在，"偏好性"应该是“客观的”和“物理真实的”,即使是应用在单个实验中。接下来我们通过数学演示看到偏好性解释将导致的一些逻辑上的困难。波普尔抱怨说，在量子理论中，人们会在"纯粹客观的统计解释和因为不完整的知识导致的主观解释"之间跳来跳去，并认为后者是应受谴责的，而偏好性解释避免了后者。他不可能错的更离谱了。在第9章中，我们在概念层面详细回答了这个问题;显然，不完整的知识是科学家唯一的工作材料！在第10章中，我们考虑了掷硬币的详细物理性质，看看解抛掷方法如何直接的,物理上的影响了掷筛子的结果。

In all the sciences, logical inference is more generally applicable. We agree that physical influences can propagate only forward in time; but logical inferences propagate equally well in either direction. An archaeologist uncovers an artifact that changes his knowledge of events thousands of years ago; were it otherwise, archaeology, geology, and paleontology would be impossible. The reasoning of Sherlock Holmes is also directed to inferring, from presently existing evidence, what events must have transpired in the past. The sounds reaching your ears from a marching band 600 meters distant change your state of knowledge about what the band was playing two seconds earlier. Listening to a Toscanini recording of a Beethoven symphony changes your state of knowledge about the sounds Toscanini elicited from his orchestra many years ago.

在所有的科学中，逻辑推理更普遍适用。我们同意物理影响只能在时间上向前传播;但逻辑推理在时间的两个方向上都同样传播。一位考古学家发现了一件文物,由此改变了他对几千年的事件的知识;如果不是这样，考古学，地质学和古生物学将是不复存在。夏洛克·福尔摩斯的推理也是从现有的证据中推断出过去一定发生了的事情。600米外行进的乐队发出的声音传到了你的耳朵,让你知道了2秒钟之前演奏的是什么(从不知道到知道)。聆听录制的托斯卡尼尼指挥的贝多芬交响曲,改变了你对许多年前托斯卡尼尼乐队发出的声音的"知识".

More generally, consider a probability distribution $$p(x_1···x_n|B)$$, where xi denotes the result of the ith trial, and could take on not just two values (red or white) but, say, the values $$x_i=(1, 2, ... , k)$$ labeling k different colors. If the probability is invariant under any permutation of the $$x_i$$ , then it depends only on the sample numbers $$(n_1···n_k)$$ denoting how many times the result $$x_i = 1$$ occurs, how many times $$x_i = 2$$ occurs, etc. Such a distribution is called exchangeable; as we shall find later, exchangeable distributions have many interesting mathematical properties and important applications.

更一般地，考虑概率分布$$p(x_1 ... x_n|B)$$，其中xi表示第i次试验的结果，并且不仅可以采用两个值(红色或白色)，而且可以值$$ x_i =(1,2，...，k)$$标记k种不同的颜色。如果概率在$$ x_i $$的任何排列下是不变的，那么它仅取决于样本数$$(n_1 ... n_k)$$表示结果$$ x_i = 1 $$出现的次数，发生了多少次$$ x_i = 2 $$等。这种分布称为可交换的;正如我们后面将要发现的那样，可交换分布具有许多有趣的数学特性和重要的应用。

As this suggests, and as we shall verify later, a fully adequate theory of nonequilibrium phenomena, such as sound propagation, also requires that backward logical inferences be recognized and used, although they do not express physical causes. The point is that the best inferences we can make about any phenomenon – whether in physics, biology, economics, or any other field – must take into account all the relevant information we have, regardless of whether that information refers to times earlier or later than the phenomenon itself; this ought to be considered a platitude, not a paradox. At the end of this chapter (Exercise 3.6), the reader will have an opportunity to demonstrate this directly, by calculating a backward inference that takes into account a forward causal influence.

正如这表明的那样，并且正如我们稍后将要验证的那样，完全足够的非平衡现象理论，例如声音传播，也需要识别和使用后向逻辑推理，尽管它们不表达物理原因。关键是我们可以对任何现象做出最好的推论 - 无论是在物理学，生物学，经济学还是其他任何领域 - 必须考虑到我们拥有的所有相关信息，无论这些信息是指时间的早期还是晚期。现象本身;这应该被认为是陈词滥调，而不是悖论。在本章的最后(练习3.6)，读者将有机会通过计算考虑到正向因果影响的后向推理来直接证明这一点。

More generally, consider a probability distribution $$p(x_1···x_n|B)$$, where $$x_i$$ denotes the result of the ith trial, and could take on not just two values (red or white) but, say, the values $$x_i=(1, 2, ... , k)$$ labeling k different colors. If the probability is invariant under any permutation of the $$x_i$$ , then it depends only on the sample numbers $$(n_1···n_k)$$ denoting how many times the result $$x_i = 1$$ occurs, how many times $$x_i = 2$$ occurs, etc. Such a distribution is called exchangeable; as we shall find later, exchangeable distributions have many interesting mathematical properties and important applications. 

更一般地，考虑概率分布$$p(x_1 ... x_n|B)$$，其中$$x_i$$表示第i次试验的结果，并且不仅可以采用两个值(红色或白色)，而且可以取值为$$x_i=(1,2，...，k)$$来标记k种不同的颜色。如果概率在$$x_i$$的任何排列下是不变的，那么它仅取决于是采样次数$$(n_1 ... n_k)$$,分别表示结果$$x_i=1$$出现的次数，结果$$x_i=2$$出现的次数,以此类推。这种分布称为可交换的;正如我们后面将要发现的那样，可交换分布具有许多有趣的数学特性和重要的应用。

Returning to our urn problem, it is clear already from the fact that the hypergeometric distribution is exchangeable that every draw must have just the same relevance to every other draw, regardless of their time order and regardless of whether they are near or far apart in the sequence. But this is not limited to the hypergeometric distribution; it is true of any exchangeable distribution (i.e. whenever the probability for a sequence of events is independent of their order). So, with a little more thought, these symmetries, so inexplicable from the standpoint of physical causation, become obvious after all as propositions of logic.

回到我们的取球问题，显而易见超几何分布是可交换的，每次抽取与所有其他的抽取具有相同的相关性，无论它们的时间顺序如何，也无论它们的次序是接近还很远。但这不仅限于超几何分布;任何可交换的分布都是如此(即，只要序列中的事件的概率与其顺序无关)。因此，经过一点思考，这些对称性是无法从物理因果关系的角度来解释，但作为逻辑命题则显而易见。

Let us calculate this effect quantitatively. Supposing j < k, the proposition $$R_jR_k$$ (red at both draws j and k) is in Boolean algebra the same as

让我们定量地计算这个结论。假设j<k，命题$$R_jR_k$$(第j次和第k次都抽出红球)在布尔代数中相等于

$$R_j R_k = (R_1 + W_1)···(R_{j−1} + W_{j−1}) R_j (R_{j+1} + W_{j+1})···(R_{k−1} + W_{k−1})R_k$$ , (3.41)

which we could expand in the manner of (3.36) into a logical sum of

按(3.36)将其展开为命题的逻辑求和

 $$2^{j−1} × 2^{k−j−1} = 2^{k−2}$$ (3.42)

propositions, each specifying a full sequence, such as

每个命题定义了一个k个结果的序列,如

$$W_1R_2W_3···R_j···R_k$$ (3.43)

of k results. The probability $$P(R_j R_k |B)$$ is the sum of all their probabilities. But we know that, given B, the probability for any one sequence is independent of the order in which red and white appear. Therefore we can permute each sequence, moving $$R_j$$ to the first position, and $$R_k$$ to the second. That is, we can replace the sequence $$(W_1···R_j···)$$ by $$(R_1 ···W_j ···)$$, etc. Recombining them, we have $$(R_1R_2)$$ followed by every possible result for draws (3, 4, . . . , k). In other words, the probability for $$R_j R_k$$ is the same as that of

概率$$P(R_jR_k|B)$$是它们所有概率的总和。 但我们知道，给定B，任何一个序列的概率与红色和白色出现的顺序无关。 因此，我们可以置换每个序列，将$$ R_j $$移动到第一个位置，将$$ R_k $$移动到第二个位置。 也就是说，我们可以用$$(R_1···W_j···)$$替换序列$$(W_1···R_j ...)$$,如此等等。重新组合它们，我们有$$(R_1R_2)$$,对应第(3,4，...，k)次可能的抽取结果。 换句话说，$$ R_j R_k $$的概率与

 $$R_1R_2(R_3 + W_3) ··· (R_k + W_k ) = R_1R_2$$, (3.44)

and we have

相等,而且有

 $$P(R_j R_k |B) = P(R_1R_2|B) = \frac {M(M − 1)} {N(N − 1)}$$ , (3.45)

and likewise

类似的有

 $$P(W_j R_k |B) = P(W_1R_2|B) = \frac {(N − M)M} {N(N − 1)}$$ . (3.46)

Therefore by the product rule

因此,对所有j<k,应用乘法规则

 $$P(R_k|R_jB)= \frac {P(R_jR_k|B)} {P(R_j|B)}  = \frac {M−1} {N−1}$$ (3.47) 
 $$P(R_k|W_jB) = \frac {p(W_jR_k|B)} {P(R_j|B)} = \frac {M} {N-1} $$  (3.48)

for all j < k. By (3.40), the results (3.47) and (3.48) are true for all j= k.

根据(3.40),对所有的j=k,(3.47)和(3.48)的结果都为真.

Since as noted this conclusion appears astonishing to many people, we shall belabor the point by explaining it still another time in different words. The robot knows that the urn originally contained M red balls and (N − M) white ones. Then, learning that an earlier draw gave red, it knows that one less red ball is available for the later draws. The problem becomes the same as if we had started with an urn of (N − 1) balls, of which (M − 1) are red; (3.47) corresponds just to the solution (3.37) adapted to this different problem.

因为如上所述这个结论让许多人感到惊讶，所以我们用另一种表述方式来再次解释一下。机器人知道盒子中最初包含M个红球和(N-M)个白球。然后，了解到之前的某次取出的是红球，所以它知道之后的在抽取中红球的个数已经变少了一个。此时问题就变成和最初在盒子中只有(N-1)个,而其中(M-1)是红色的情况一样;(3.47)只是让(3.37)适用于这个新问题的解决方案而已。

But why is knowing the result of a later draw equally cogent? Because if the robot knows that red will be drawn at any later time, then in effect one of the red balls in the urn must be ‘set aside’ to make this possible. The number of red balls which could have been taken in earlier draws is reduced by one, as a result of having this information. The above example (3.38) is an extreme special case of this, where the conclusion is particularly obvious.

但是为什么知道后面的抽取的结果有同样的说服力呢？因为如果机器人知道以后会抽出红球，那么实际上必须“留出”盒子中的一个红色球以使让这变得可能。由于获得了这些信息，所以在之前的抽取中可被取出的红球数量减少了一个。上面的例子(3.38)只是一个结论及其显而易见的极端特例。
