== 3.3 Reasoning from less precise information 基于非精准信息进行推断

Now let us try to apply this understanding to a more complicated problem. Suppose the robot learns that red will be found at least once in later draws, but not at which draw or draws this will occur. That is, the new information is, as a proposition of Boolean algebra,

现在让我们尝试将这种理解应用于更复杂的问题。假设机器人知道,在某次抽取或者几次抽取中不会抽到红球,但在之后的某些抽取中至少有一个红球。也就是说，作为布尔代数的命题，新信息是

 $$R_{later} ≡ R_{k+1} + R_{k+2} + ···+ R_n$$. (3.49)

This information reduces the number of red available for the kth draw by at least one, but it is not obvious whether $$R_{later}$$ has exactly the same implications as does $$R_n$$. To investigate this we appeal again to the symmetry of the product rule:

此信息使得第k次中可抽取到的红球数量至少减少了一个，但是$$R_ {later}$$与$$R_n$$具有相同的含义,这一点并不明显。为了说明这一点，我们需要再次应用乘法规则的对称性：

 $$P(R_k R_{later}|B) = P(R_k |R_{later}B)P(R_{later}|B) = P(R_{later}|R_k B)P(R_k |B)$$, (3.50)

which gives us

由此得到

 $$P(R_k |R_{later}B) = P(R_k |B) \frac {P(R_{later}|R_k B)} {P(R_{later}|B)},$$ (3.51)

and all quantities on the right-hand side are easily calculated.

式子右侧的数值很容易计算.

Seeing (3.49), one might be tempted to reason as follows:

参考(3.49),有人可能试图做如下推断:

 $$P(R_{later}|B) = \sum _{j=k+1} ^n P(R_j |B),$$ (3.52)

but this is not correct because, unless M = 1, the events $$R_j$$ are not mutually exclusive, and, as we see from (2.82), many more terms would be needed. This method of calculation would be very tedious.

但这是错误的，因为除非M=1，否则事件$$R_j$$之间不是互斥的，而且，正如从(2.82）看到的那样，计算中还需要包括更多的项。这种计算方法可能是非常繁琐的。

To organize the calculation better, note that the denial of $$R_{later}$$ is the statement that white occurs at all the later draws:

为了简化计算,注意$$R_{later}$$的否定表述的是之后取出的都是白球:

 $$\bar{R}_{later} = W_{k+1} W_{k+2} ···W_n.$$ (3.53)

So $$P(\bar{R}_{later}|B)$$ is the probability for white at all the later draws, regardless of what happens at the earlier ones (i.e. when the robot does not know what happens at the earlier ones). By exchangeability this is the same as the probability for white at the first (n − k) draws, regardless of what happens at the later ones; from (3.13),

所以$$P(\bar{R}_{later}|B)$$表示的是所有之后取出的都是白球的概率，无论之前发生了什么(相当于机器人不知道在之前都抽到了什么球）。通过可交换性可知，这与头(n-k）次都抽出了白球的概率相同，而不管之后抽到的是什么; 由(3.13）,

 $$P(\bar{R}_{later}|B) = \frac {(N−M)!(N−n+k)!} {N!(N−M−n+k)!} = \binom {N−M} {n−k} \binom {N} {n−k}^{−1} .$$ (3.54)

Likewise, $$P(\bar{R}_{later}|R_kB)$$ is the same result for the case of (N−1) balls, (M−1) of which are red:

类似的,$$P(\bar{R}_{later}|R_kB)$$和(N-1)个球其中(M-1)为红球时的结果一样,

 $$P(\bar{R}_{later}|R_kB)=\frac{(N−M)!}{(N−1)!} \frac{(N−n+k−1)!}{(N−M−n+k)!}= \binom {N−M} {n−k} \binom {N−1}{n−k}^{−1}.$$ (3.55)

Now (3.51) becomes

现在(3.51)变为

 $$P(R_k|R_{later}B) = \frac {M}{N−n+k} × \frac { \binom {N−1}{n−k} − \binom {N−M}{n−k} } { \binom {N}{n−k} − \binom {N−M}{n−k} }$$ . (3.56)

As a check, note that if n = k + 1, this reduces to (M − 1)/(N − 1), as it should.

可以验证,当n=k+1时,将归结为(M-1)/(N-1),正如我们期望的那样.

At the moment, however, our interest in (3.56) is not so much in the numerical values, but in understanding the logic of the result. So let us specialize it to the simplest case that is not entirely trivial. Suppose we draw n = 3 times from an urn containing N = 4 balls, M = 2 of which are white, and ask how knowledge that red occurs at least once on the second and third draws affects the probability for red at the first draw. This is given by (3.56) with N = 4, M = 2, n = 3, k = 1:

然而，目前我们对(3.56）的兴趣并不是数值，而是理解结果表达出来的逻辑。因此，让我们专注于最简单的非平凡的例子。假设盒子中有N=4个球，其中M=2个是白球,从中抽n=3次，问在第二次和第三次抽中红球至少出现一次的知识,是如何影响第一次抽中红球的概率。这由(3.56）给出，其中N=4，M=2，n=3，k=1：

 $$P(R_1|R_2 + R_3, B) = \frac {6 − 2} {12 − 2} = \frac 2 5 = ( \frac 1 2 ) \frac {1 − 1/3}{1 − 1/6},$$ (3.57)

the last form corresponding to (3.51). Compare this to the previously calculated probabilities:

最后的形式对应了(3.51).

 $$P(R_1|B) = \frac 1 2, P(R_1|R_2B) = P(R_2|R_1B) = \frac 1 3 $$. (3.58)

What seems surprising is that

有点以外的是

 $$P(R_1|R_{later}B) > P(R_1|R_2B)$$. (3.59)

Most people guess at first that the inequality should go the other way; i.e. knowing that red occurs at least once on the later draws ought to decrease the chances of red at the first draw more than does the information $$R_2$$. But in this case the numbers are so small that we can check the calculation (3.51) directly. To find $$P(R_{later}|B)$$ by the extended sum rule (2.82) now requires only one extra term:

大多数人一开始觉得不等式应该反过来;即红色在之后的抽取中至少出现一次的信息,应该比信息$$R_2$$,让第一次就抽中红球的机会变得更少。但在本例中，因为总数太小，我们可以直接检查(3.51）中的计算。用扩展加法法则(2.82）来得出$$P(R_{later}|B)$$，现在需要再多一个额外的项：

 $$P(R_{later}|B) = P(R_2|B) + P(R_3|B) − P(R_2R_3|B) $$
 $$= \frac 1 2 + \frac 1 2 − \frac 1 2 × \frac 1 3 = \frac 5 6 $$. (3.60)

We could equally well resolve $$R_{later}$$ into mutually exclusive propositions and calculate

我们同样可以将$$R_{later}$$解析为彼此互斥的命题,并计算

 $$P(R_{later}|B) = P(R_2W_3|B) + P(W_2R_3|B) + P(R_2R_3|B) $$
 $$ = \frac 1 2 × \frac 2 3 + \frac 1 2 × \frac 2 3 + \frac 1 2 × \frac 1 3 = \frac 5 6 . $$   (3.61)

The denominator (1 − 1/6) in (3.57) has now been calculated in three different ways, with the same result. If the three results were not the same, we would have found an inconsistency in our rules, of the kind we sought to prevent by Cox’s functional equation arguments in Chapter 2. This is a good example of what ‘consistency’ means in practice, and it shows the trouble we would be in if our rules did not have it.

(3.57）中的分母(1-1/6）现在以三种不同的方式来计算，而结果相同。如果三个结果不一样，我们就会发现我们的规则中存在着不一致，而我们曾试图通过第2章中的讨论到的Cox函数方程来防止这种情况。这是“一致性”在实践中意味着什么的一个很好的例子，它显示如果我们的规则不满足一致性时我们会遇到的麻烦。

Likewise, we can check the numerator of (3.51) by an independent calculation:

类似的,通过独立计算来检验(3.51)中的分子

 $$P(R_{later}|R_1B) = P(R_2|R_1B) + P(R_3|R_1B) − P(R_2R_3|R_1B) $$
 $$ = \frac 1 3 + \frac 1 3 − \frac 1 3 × 0 = \frac 2 3$$ , (3.62)

and the result (3.57) is confirmed. So we have no choice but to accept the inequality (3.59) and try to understand it intuitively. Let us reason as follows. The information $$R_2$$ reduces the number of red balls available for the first draw by one, and it reduces the number of balls in the urn available for the first draw by one, giving $$P(R_1|R_2B) = (M − 1)/(N − 1) = 1/3$$. The information $$R_{later}$$ reduces the ‘effective number of red balls’ available for the first draw by more than one, but it reduces the number of balls in the urn available for the first draw by two (because it assures the robot that there are two later draws in which two balls are removed). So let us try tentatively to interpret the result (3.57) as

结果(3.57）得到确认。所以我们别无选择，只能接受不等式(3.59），并尝试直观地理解它。让我们推理如下。信息$$R_2$$使得第一次抽取到的红球数量减少一个，并且将第一次抽取的总可抽取球数减少了一个，得到$$P(R_1|R_2B）=(M-1）/(N-1）=1/3 $$。 信息$$R_{later} $$使得第一次抽取可用的红球的数量减少了不止一个，但它让第一次抽取时可用的球的总数量减少了两个(因为它保证了机器人之后还有抽取两次，即排除了两个球）。因此，让我们临时试图将结果(3.57）解释为

 $$P(R_1|R_{later}B) = \frac {(M)_{eff}} {N − 2} $$, (3.63)

although we are not quite sure what this means. Given $$R_{later}$$, it is certain that at least one red ball is removed, and the probability that two are removed is, by the product rule:

虽然我们不大确定这表示了什么.给定$$R_{later}$$,可以确定至少有一个红球被去掉了,根据乘法规则而有两个被去掉的概率是:

 $$P(R_2R_3|R_{later}B) = \frac {P(R_2R_3R_{later}|B)} {P(R_{later}|B)} = \frac {P(R_2R_3|B)}{P(R_{later}|B)} $$
 $$ = \frac {(1/2) × (1/3)} {5/6} = \frac 1 5 $$ (3.64)

because $$R_2R_3$$ implies $$R_{later}$$; i.e. a relation of Boolean algebra is $$(R_2R_3R_{later} = R_2R_3)$$. Intuitively, given $$R_{later}$$ there is probability 1/5 that two red balls are removed, so the effective number removed is 1 + (1/5) = 6/5. The ‘effective’ number remaining for draw one is 4/5. Indeed, (3.63) then becomes

因为$$R_2R_3$$蕴含了$$R_{later}$$;例如,逻辑代数关系为$$(R_2R_3R_{later} = R_2R_3)$$.直觉上,给定$$R_{later}$$则两个红球被去掉的概率是1/5,所以被去掉的有效值是1+(1/5)=6/5.再取出一个球后的"有效"值为4/5.事实上,(3.63)则变为

 $$P(R_1|R_{later}B) = \frac {4/5}{2} = \frac 2 5 $$, (3.65)

in agreement with our better motivated, but less intuitive, calculation (3.57).

和我们最期望的(3.57)的计算一致,但不那么符合直觉.
