== 3.5 Other forms and extensions

The hypergeometric distribution (3.22) can be written in various ways. The nine factorials can be organized into binomial coefficients also as follows:

 $$h(r|N,M,n)= \frac { \binom {n} {r} \binom {N−n} {M−r} } { \binom {N} {M} }$$  . (3.73)

But the symmetry under exchange of M and n is still not evident; to see it we must write out (3.22) or (3.73) in full, displaying all the individual factorials.

但是M和n交换时的对称性仍然不明显; 要看到它，我们必须完整地写出（3.22）或（3.73），显示所有个别因子。

We mayalso rewrite (3.22), as an aid to memory, in a more symmetric form: the probability for drawing exactly r red balls andw white ones in n = r + w draws, from an urn containing R red and W white, is

我们也可以用更加对称的形式重写（3.22）作为记忆的辅助：从包含R红色和W白色的骨灰盒中，在n = r + w绘制中精确绘制红色球和白色球的概率是

 $$h(r) = \frac { \binom {R} {r} \binom {W} {w} } { \binom {R + W} {r + w} } $$  , (3.74)

and in this form it is easily generalized. Suppose that, instead of only two colors, there are k different colors of balls in the urn, $$N_1$$ of color 1, $$N_2$$ of color 2, ... , $$N_k$$ of color k. The probability for drawing $$r_1$$ balls of color 1, $$r_2$$ of color 2, ... , $$r_k$$ of color k in $$n = \sum r_i$$ draws is, as the reader may verify, the generalized hypergeometric distribution:

在这种形式下，它很容易推广。 假设，而不是只有两种颜色，在urn中有k种不同颜色的球，颜色1的$$ N_1 $$，颜色2的$$ N_2 $$，...，颜色k的$$ N_k $$。 在$$ n = \ sum r_i $$中绘制颜色1，$$ r_2 $$颜色2，...，$$ r_k $$颜色k的$$ r_1 $$球的概率为， 读者可以验证，广义超几何分布：

 $$h(r_1 ··· r_k |N_1 ··· N_k) = \frac { \binom {N_1} {r_1} ··· \binom {N_k} {r_k} } { \binom {\sum N_i} {\sum r_i}} $$  . (3.75)

