= 3 Elementary sampling theory 基本采样理论

At this point, the mathematical material we have available consists of the basic product and sum rules

目前为止,在数学上我们得到了乘法和基础的加法规则:

 $$ P(AB|C)=P(A|BC)P(B|C)=P(B|AC)P(A|C) $$  (3.1)
 $$ P(A|B)+P(\bar{A}|B)=1 $$  (3.2)

from which we derived the extended sum rule

由此扩展出加规则

 $$ P(A+B|C)=P(A|C)+P(B|C)-P(AB|C) $$  (3.3)

and with the desideratum (IIIc) of consistency, the principle of indifference: if on background information B the hypotheses $$(H_1,...,H_n)$$ are mutually exclusive and exhaustive, and B does not favor any one of them over any other, then

根据一致性公理(IIIc),即无差异原理:如果基于背景信息B,假设的集合$$(H_1,...,H_n)$$是互斥且穷尽的,而且B对任何一个没有偏好,则

 $$ P(H_i|B)={1 \over N}, 1 \le i \le N. $$    (3.4)

From (3.3) and (3.4) we then derived the Bernoulli urn rule: if B specifies that A is true on some subset of M of the H i , and false on the remaining (N − M), then

从(3.3)和(3.4)我们得出伯努利采样规则,如果B规定了对$$H_i$$的一个子集M有A为真,且对剩余的(N-M)为假,则

 $$ P(A|B)={M \over N}. $$    (3.5)

It is important to realize how much of probability theory can be derived from no more than this.

重要的是看看只用上述规则可以得出多少概率论中的结果。

In fact, essentially all of conventional probability theory as currently taught, plus many important results that are often thought to lie beyond the domain of probability theory, can be derived from the above foundation. We devote the next several chapters to demonstrating this in some detail, and then in Chapter 11 we resume the basic development of our robot’s brain, with a better understanding of what additional principles are needed for advanced applications.

事实上，目前教授的所有传统概率理论，包括许多重要结论,这些结论常常被认为是超出概率论之外的，都可以从上面的规则推导而来。在接下来的几章中，我们将展示各种细节，然后在第11章中再回到设计机器人大脑的问题，伴随着对高级应用所需的其他的原则的更好理解。

The first applications of the theory given in this chapter are, to be sure, rather simple and naive compared with the serious scientific inference that we hope to achieve later. Nevertheless, our reason for considering them in close detail is not mere pedagogical form. Failure to understand the logic of these simplest applications has been one of the major factors retarding the progress of scientific inference – and therefore of science itself – for many decades. Therefore we urge the reader, even one who is already familiar with elementary sampling theory, to digest the contents of this chapter carefully before proceeding to more complicated problems.

本章中首先给出的应用是非常简单和原始的，和我们之后希望得到的严肃的科学推断相比。尽管如此，我们详细考察这些细节并不是为了教学的缘故。由于没能正确理解这些简单应用的逻辑，是多年来阻碍了科学推理--因此也阻碍了科学自己--发展的重要因素。因此我们要求读者，即使你已经对基本采样理论了熟于胸，在研究接下来的复杂问题之前，也请认真的咀嚼一下本章的内容。
